import json
from pathlib import Path
P=Path(__file__).parent;nodes=[];edges=[]
slugs=['3-2-1-rotation-matrices-part-1-of-2','3-2-1-rotation-matrices-part-2-of-2','3-3-1-homogeneous-transformation-matrices','2-2-degrees-of-freedom-of-a-robot','2-3-2-configuration-space-representation','2-5-task-space-and-workspace','forward-kinematics-example','inverse-kinematics-of-open-chains','5-1-1-space-jacobian','5-3-singularities']
sources={str(i):{'title':s.replace('-',' '),'url':'https://modernrobotics.northwestern.edu/nu-gm-book-resource/'+s+'/','accessed':'2026-09-14'} for i,s in enumerate(slugs)}
def ref(s):return 'sss-rob-'+s[1:] if s.startswith('@') else s
def edge(a,b,t,r):edges.append(dict(source=ref(a),target=ref(b),type=t,rationale=r,authorship='editorial'))
def add(k,name,a,b,criterion,place,source,deps,parent):
 nodes.append(dict(id=ref('@'+k),name=name,domain='Robotics',subdomain='Frames and kinematics foundations',icon='robot',description=a.split('. ')[0]+'.',details=a+'\n\n'+b,proficiency80=None,pinned=False,sourceRefs=[str(source)],proficiencyReference=criterion,placementNote=place,scopeNote='Right-handed frames, column vectors, ideal rigid links, and explicitly stated joint conventions.',authoringOrigin='sss-robotics-foundations-batch-01',contentAuthorship='Original editorial decomposition; sources support concepts, not official prerequisite links.',layoutRequest={'position':'assign-after-merge','referenceLevel':'derive-after-merge','preserveExistingPositions':True}))
 for x,reason in deps:edge(x,'@'+k,'prerequisite',reason)
 if parent not in [x for x,_ in deps]:edge(parent,'@'+k,'related','This operation is part of the existing broader topic and is made independently markable without copying its proficiency.')
add('frame-labels','Label the reference frame of a robot position or direction',
'Attach a frame label to coordinate values before combining them. A point reported by a camera and a point reported in the robot base cannot be directly compared unless their reference frames agree.',
'State the origin and axis directions used by each frame in a sketch or calculation. Changing coordinates can describe the same physical object; a different coordinate tuple does not necessarily mean that object moved.',
'I can identify which frame each coordinate tuple belongs to and flag incompatible comparisons.','This establishes the notation needed before applying frame conversions.',1,[('m-vector','Coordinate tuples and vector components must already be understood.')],'r-frame')
add('rotation-columns','Construct a rotation matrix from one frame’s axes expressed in another',
'Form R_AB by placing the three unit axes of frame B, expressed in frame A, into its columns. Under the column-vector convention, multiplying R_AB by B components produces A components.',
'Check a simple axis-aligned example before using arbitrary orientations. Reversing the frame labels changes the mapping, so copying the same numeric matrix into both directions generally gives an incorrect result.',
'I can build R_AB from labeled axes and use its columns to explain the mapping.','This turns frame notation into a concrete orientation representation.',0,[('@frame-labels','The source and destination frames determine which axes populate the columns.'),('m-matrix','Matrix columns and multiplication are required.')],'r-rigid')
add('rotation-check','Check whether a supplied matrix represents a proper 3D rotation',
'Check that R transpose times R equals the identity and that the determinant is positive one. Orthogonal columns alone can also describe a reflection, which is not a proper rotation.',
'For rounded numerical data, use a stated tolerance instead of exact floating-point equality. Reject scaling or reflection as orientation changes; this check diagnoses an invalid input rather than automatically repairing it.',
'I can distinguish a proper rotation from a reflection or scaled matrix using explicit checks.','This checks the orientation representation before it is trusted in a transform.',0,[('@rotation-columns','The columns must represent a right-handed orthonormal frame.')],'r-rigid')
add('point-direction','Apply translation to a point but not to a free displacement vector',
'For a rigid coordinate conversion use p_A=R_AB p_B+t_AB for a point and d_A=R_AB d_B for a free displacement vector. The translation locates an origin, not a direction.',
'Compare a pair of transformed points to confirm that their difference rotates without the translation term. This rule does not by itself transform derivatives measured by moving observers, which require additional motion terms.',
'I can convert a point and a free displacement vector without applying the same translation to both.','This distinguishes two uses of the same frame conversion.',1,[('@rotation-columns','Rotation re-expresses components before a point receives an origin offset.')],'r-frame')
add('compose','Compose a chain of labeled rigid transforms in the correct order',
'With T_AB mapping B coordinates into A coordinates, combine successive mappings as T_AC=T_AB T_BC. Intermediate frame labels must match, and the rightmost transformation acts first on a column point vector.',
'Keep the multiplication order explicit even when a particular example accidentally commutes. Check the chain with a point of known location; a valid matrix size alone does not prove that the frames connect correctly.',
'I can assemble a base-to-sensor transform from a labeled chain without reversing its order.','This builds longer coordinate conversions from individual point mappings.',2,[('@point-direction','Each transform must have a known mapping meaning.'),('m-matrix','Composition uses matrix multiplication.')],'r-rigid')
add('inverse','Invert a rigid transform while rotating its translation correctly',
'For T_AB with rotation R and translation t, form T_BA using R transpose and translation minus R transpose times t. Negating t without re-expressing it in the inverse frame is generally wrong.',
'Check the result by applying the forward and inverse mappings to the same point. The round trip should return the original coordinates within numerical tolerance, provided the original rotation matrix was valid.',
'I can invert a rigid transform and verify a point round trip.','This provides the reverse mapping needed when a transform is supplied in the opposite direction.',2,[('@point-direction','The original translation and rotation must be interpreted together.'),('@rotation-check','The transpose inverse formula assumes a valid rotation.')],'r-rigid')
add('serial-dof','Count independent coordinates of an unconstrained serial joint chain',
'For a fixed-base open chain of independent one-degree-of-freedom revolute or prismatic joints, count one configuration coordinate per joint. Record whether each coordinate measures an angle or a translation.',
'Do not equate this count with motor count or independent end-effector task directions. Closed loops, mechanical coupling, and additional constraints require a separate mobility analysis, so the simple counting rule must stay within its assumptions.',
'I can count configuration variables for an independent open chain and identify when the rule no longer applies.','This gives a bounded starting case within the broader degrees-of-freedom topic.',3,[],'r-dof')
add('joint-conventions','Specify joint order, zero references, signs, and units for a configuration',
'Define a configuration vector by listing joint coordinates in a fixed order with their units, positive directions, and zero references. The same numeric list can describe different poses when these conventions differ.',
'For a serial planar arm, distinguish an elbow angle relative to the first link from an absolute angle in the base frame. Preserve the convention in diagrams and calculations rather than silently switching interpretations.',
'I can explain every entry in a joint configuration and distinguish relative from absolute joint angles.','This makes the independent coordinates usable in a reproducible kinematic calculation.',4,[('@serial-dof','The independent joint coordinates must first be identified.'),('m-radian','Angular coordinates require a clear unit convention.')],'r-configuration')
add('task-coordinates','Distinguish joint configuration, task coordinates, and reachable workspace',
'Joint coordinates describe the robot arrangement, while task coordinates describe the output specified for a job. A position-only task imposes different requirements from a task that also specifies tool orientation.',
'Workspace describes the outputs a robot can reach under stated limits. Reaching a point does not establish that every orientation at that point is possible, and different joint configurations may produce the same requested output.',
'I can state whether a target specifies position, orientation, or both and distinguish it from joint configuration.','This defines what a forward or inverse kinematics problem is trying to represent.',5,[('@joint-conventions','Configuration variables must be distinguished from the requested output coordinates.')],'r-configuration')
add('planar-fk','Calculate position and orientation of an ideal two-revolute-link planar arm',
'For link lengths L1 and L2, shoulder angle q1, and relative elbow angle q2, compute x=L1 cos(q1)+L2 cos(q1+q2) and y=L1 sin(q1)+L2 sin(q1+q2). Tool orientation along the second link is q1+q2.',
'Use a fixed base, consistent angle units, and a tip at the second link end. Compare straight and right-angle configurations to catch relative-angle mistakes; compliance and calibration errors are outside this nominal geometric calculation.',
'I can compute the ideal planar tip position and orientation from two joint angles.','This applies joint conventions and trigonometry to a complete small forward model.',6,[('@joint-conventions','The second angle is relative to the first link.'),('m-unitcircle','Sine and cosine resolve each link into base-frame components.')],'r-forward')
add('tool-offset','Include a fixed tool offset after the final link transform',
'When the tool frame is displaced from the last link frame, append the fixed link-to-tool transform to the chain. The resulting base-to-tool transform identifies the tool pose rather than just the flange pose.',
'Rotate an offset expressed in local link coordinates before interpreting it in the base frame. Adding a local offset directly to base coordinates gives the wrong location whenever those frame axes differ.',
'I can locate an offset tool point without confusing local and base coordinates.','This extends transform composition to a common end-effector modeling requirement.',6,[('@compose','A fixed terminal transform must be appended in the correct order.')],'r-forward')
add('planar-reach','Check the geometric position reach of an unrestricted planar two-link arm',
'For positive link lengths and unrestricted revolute angles, a target distance r from the base is reachable in position when abs(L1-L2) is at most r and r is at most L1+L2.',
'This annular test ignores obstacles, joint stops, and requested tool orientation. A passing result permits an ideal position solution but does not establish a usable motion or an achievable full pose.',
'I can distinguish geometric position reachability from limits, obstacles, and pose feasibility.','This screens the planar inverse problem before calculating individual joint solutions.',5,[('@task-coordinates','The check concerns position reach rather than arbitrary pose.'),('m-norm','Target radius is calculated from its position components.')],'r-inverse')
add('planar-ik','Calculate both regular inverse-kinematic branches of a planar two-link arm',
'For a reachable position, compute c2=(x*x+y*y-L1*L1-L2*L2)/(2*L1*L2) and q2=plus or minus acos(c2). For each branch use q1=atan2(y,x)-atan2(L2 sin(q2),L1+L2 cos(q2)). These angles use the shoulder and relative elbow conventions of the forward model.',
'Retain both regular branches before selecting one. At straight or folded boundaries they can coincide, and equal links at the base origin have a special nonunique case; do not force that case through an undefined angle formula.',
'I can compute both regular position solutions and recognize the named degenerate cases.','This solves the screened planar position problem using quadrant-aware inverse trigonometry.',7,[('@planar-reach','Geometric reach must be checked before taking inverse cosine.'),('m-invtrig','Inverse trigonometric branches and quadrants determine valid joint angles.'),('@planar-fk','The inverse calculation depends on the same link and joint conventions.')],'r-inverse')
add('ik-verification','Verify an inverse-kinematic candidate by forward substitution and joint limits',
'Substitute a candidate configuration into the forward model and compare the output with the requested target using stated tolerances. Check each joint against its actual allowed interval and winding convention.',
'A correct position residual does not prove orientation agreement or collision freedom. Report which checks were performed rather than treating a solver output as an automatically executable robot command.',
'I can reject a candidate that misses its target or violates a joint limit and state the remaining checks.','This follows inverse solution generation and separates solving equations from accepting a usable candidate.',7,[('@planar-ik','Candidate joint solutions are the inputs to this verification step.')],'r-inverse')
add('position-jacobian','Derive the Cartesian position Jacobian of a planar two-link arm',
'Differentiate the two planar tip-position equations with respect to q1 and q2. Arrange the derivatives in a two-by-two matrix whose rows correspond to x and y and whose columns correspond to the joints.',
'Use radians for angular derivatives and preserve the row and column order. This is a position Jacobian; a spatial twist Jacobian or a pose-parameter derivative may have different rows and interpretations.',
'I can derive the planar position Jacobian and state the meaning of its rows and columns.','This connects the forward position model to local velocity relationships.',8,[('@planar-fk','The position equations are differentiated.'),('m-partial','Each column differentiates with respect to one joint coordinate.'),('m-transdiff','Derivatives of sine and cosine determine the entries.')],'r-jacobian')
add('joint-to-tip-rate','Calculate instantaneous planar tip velocity from joint rates',
'Evaluate the position Jacobian at the current configuration and multiply it by the joint-rate vector. The result is instantaneous tip velocity expressed in the same Cartesian frame used for the position equations.',
'Keep revolute rates in radians per second when using radian-based derivatives. The same rates can produce different velocities at different configurations; a single local Jacobian is not an exact finite-motion model over a large joint change.',
'I can calculate tip velocity and explain why the current configuration matters.','This uses the derived Jacobian as a local velocity map.',8,[('@position-jacobian','The evaluated matrix maps joint rates into Cartesian position rates.'),('m-matrix','The mapping requires matrix-vector multiplication.')],'r-jacobian')
add('planar-singularity','Identify lost instantaneous motion directions at a planar arm singularity',
'For the two-link position task, the Jacobian determinant is L1*L2*sin(q2). With positive link lengths it vanishes when the links are straight or folded, and the velocity map loses rank.',
'Inspect the available velocity directions rather than saying the robot cannot move at all. At full extension, radial tip velocity is unavailable to first order; inward displacement can still develop through a finite joint motion.',
'I can identify the planar singular configurations and explain the local motion restriction.','This interprets the velocity map where independent task directions are lost.',9,[('@joint-to-tip-rate','Available directions must be understood through the instantaneous velocity mapping.')],'r-singular')
edge('@ik-verification','r-planning','supports','Checking candidate configurations supports planning but does not replace collision checking or path generation.')
edge('@compose','c-transforms','supports','Explicit frame-chain conventions provide checks for a software transform implementation.')
edge('@planar-singularity','r-trajectory','supports','Local loss of motion directions matters when choosing feasible timed motions.')
b=dict(format='sss-content-authoring-batch',formatVersion=1,batchId='sss-robotics-foundations-batch-01',date='2026-09-14',status='Frames and introductory kinematics expansion; not a complete robotics curriculum',nodes=nodes,edges=edges,sources=sources,integration={'notAnOpenMapFile':True,'requiredContentBatches':[],'preserveExistingNodes':True,'newProficiency':None},deferred=['Moving-observer velocity transformations and spatial twists','Euler angles, quaternions, exponential coordinates and screw theory','Closed-chain mobility and loop constraints','General spatial forward kinematics and DH conventions','Numerical inverse kinematics and redundancy resolution','Full spatial Jacobians, manipulability and force mappings','Dynamics, actuation, controls, perception, planning and integration'])
(P/'robotics-foundations-batch-01.json').write_text(json.dumps(b,indent=2,ensure_ascii=False)+'\n');print(len(nodes),'skills',len(edges),'relationships')
