// Data structures and algorithms. Original descriptions; references are coverage checks only.
export const subdomain = 'Data structures and algorithms';
export const nodes = [
  { id: 'c-arrays', name: 'Arrays and dynamic arrays', icon: 'matrix', refs: ['MIT6006', 'CS2023'],
    after: { 'c-collections': 'An array is the storage structure behind a list, so using lists comes first.' },
    helpedBy: { 'm-complexity': 'Growth-rate notation expresses the constant-time and linear-time costs compared here.' },
    summary: 'Use contiguous, indexed storage and predict the cost of indexing, appending, inserting, and removing elements.',
    details: `An array stores elements side by side in memory, so the location of element i is the start address plus i times the element size. That makes reading or writing any index a constant-time operation. A fixed array, as in C, cannot grow. A dynamic array, such as a Python list or a C++ std::vector, grows by allocating a larger block and copying the elements across; because the capacity grows by a constant factor, appending is constant time on average (amortized), even though an individual append occasionally copies everything.

Inserting or removing at the front, or anywhere but the end, shifts every later element and so costs time proportional to the length. Two-dimensional data is usually stored row by row in one block, so the element at (row, col) of a W-wide image is at row * W + col. You can explain why repeatedly removing the first item of a million-element list is slow and choose a better structure, and you can compute buffer offsets for multidimensional data.` },
  { id: 'c-linked-lists', name: 'Linked lists', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'c-references': 'Each node refers to the next node, so references between objects must be understood.', 'c-objects': 'List nodes are small objects with a value and a link.' },
    summary: 'Build sequences from nodes that point to the next node, and compare their insertion and access costs with arrays.',
    details: `A linked list stores each element in a separate node that holds a value and a reference to the next node; a doubly linked list also points back to the previous node. Inserting or removing next to a node you already hold only rewires a pointer or two, so it takes constant time. Reaching the k-th element, however, means walking k links from the head, and nodes scattered through memory make that walk slower in practice than scanning an array.

Typical bugs come from rewiring in the wrong order: overwriting a node's next reference before saving it loses the rest of the list, and forgetting that the last node points to nothing causes a crash at the end. The same node-and-link idea extends to trees and graphs. You can implement insert-after and delete, reverse a singly linked list in place and explain when an array is still the better choice despite its slower insertion.` },
  { id: 'c-stacks', name: 'Stacks', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'c-arrays': 'A stack is usually implemented on the end of a dynamic array.' },
    related: { 'c-recursion': 'Recursive calls are managed on the call stack, and any recursion can be rewritten with an explicit stack.' },
    summary: 'Use a last-in, first-out stack for push and pop, and recognize problems it fits, such as nesting, undo, and backtracking.',
    details: `A stack allows access only at one end: push adds an item on top, pop removes the most recently added item and peek reads it without removing it. On the end of a dynamic array each of these takes constant time. The last-in, first-out order fits any problem in which the most recent unfinished thing must be dealt with first.

Checking that brackets in "(a[b]{c})" are balanced is the classic example: push each opening bracket and pop when a closing bracket arrives, failing on a mismatch or leftovers. Undo histories, depth-first search and expression evaluation use the same pattern, and the program's call stack holds each active function call as a frame, which is why runaway recursion ends in a stack overflow. You can trace a stack through a bracket-matching or backtracking problem step by step.` },
  { id: 'c-queues', name: 'Queues and ring buffers', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'c-arrays': 'A ring buffer is a fixed array with wrapping head and tail indices.' },
    helpedBy: { 'm-modular': 'Index wraparound in a ring buffer is arithmetic modulo the buffer capacity.' },
    summary: 'Use first-in, first-out queues, including fixed-size ring buffers that wrap around, to pass items on in arrival order.',
    details: `A queue releases items in the order they arrived: enqueue at the back, dequeue from the front. Removing from the front of a plain list shifts every element, so queues use a double-ended queue such as collections.deque or a ring buffer: a fixed array with a head index for reading and a tail index for writing, each advancing modulo the capacity, so in an 8-slot buffer the index after 7 wraps to 0. A count, or one deliberately unused slot, distinguishes a full buffer from an empty one.

When a bounded queue fills up, something must give: the writer blocks, the newest item is dropped or the oldest is overwritten. Overwriting suits a stream where only the latest sensor sample matters, but not a queue of motor commands. Ring buffers sit behind serial receive buffers, hand data from interrupt handlers or producer threads to consumers, and drive breadth-first search. You can implement a ring buffer, trace its wraparound and choose an overflow policy for a given data stream.` },
  { id: 'c-hash-tables', name: 'Hash tables', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'c-arrays': 'A hash table stores entries in an array of buckets indexed by the hash.', 'c-collections': 'Dictionaries and sets are the everyday interface to hash tables.' },
    helpedBy: { 'm-modular': 'Reducing a hash value to a bucket index is a remainder operation.' },
    summary: 'Explain how hashing gives near-constant-time lookup by key, and what collisions, load factor, and hashable keys mean.',
    details: `A hash table turns a key into an integer with a hash function and reduces that integer to a bucket index in an array. Lookup, insertion and deletion then go straight to one bucket instead of searching every entry. Different keys can land in the same bucket, a collision, which is resolved by keeping a short list per bucket or by probing for another free slot. Keeping the table only partly full, its load factor, and resizing when it fills keeps the average cost constant; a poor hash function that sends many keys to one bucket degrades lookups to a linear search.

Python's dictionaries and sets are hash tables. Keys must be hashable and must not change while stored, because a changed key hashes to a different bucket and is effectively lost, which is why a list cannot be a dictionary key but a tuple can. You can explain why checking membership in a set of 100,000 names stays fast while searching a list slows down, and why iteration order does not follow key order.` },
  { id: 'c-recursion', name: 'Recursion', icon: 'code', refs: ['MIT6006', 'PYTUT', 'CS2023'],
    after: { 'c-functions': 'A recursive function is a function that calls itself.', 'c-conditions': 'The base case that stops recursion is selected by a condition.' },
    helpedBy: { 'm-induction': 'Arguing that a recursive function is correct follows the base-case-and-step structure of induction.' },
    summary: 'Solve a problem by having a function call itself on smaller inputs, with a base case that ends the recursion.',
    details: `A recursive function handles the smallest case directly, the base case, and reduces every other case to a smaller instance of the same problem. Summing a list is the first element plus the sum of the rest, and counting files in nested folders is the files here plus the count inside each subfolder. Every call gets its own frame on the call stack, holding its own local variables until it returns.

Recursion fails when the base case is missing or never reached, and when depth exceeds the stack limit, which in Python is about 1,000 calls by default. Naive recursion can also repeat work enormously: computing Fibonacci numbers by two recursive calls takes exponential time, while remembering earlier results (memoization) makes it linear. Any recursion can be rewritten as a loop with an explicit stack. You can write a recursive solution for a nested structure, trace its call stack for a small input and convert a simple recursive function into an iterative one.` },
  { id: 'c-trees', name: 'Trees and binary search trees', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'c-linked-lists': 'Tree nodes link to children in the same way list nodes link to the next node.', 'c-recursion': 'Tree traversal and search are naturally recursive.' },
    helpedBy: { 'm-tree': 'The graph-theory view of trees supplies the vocabulary of root, parent, child, leaf, and path used here.' },
    summary: 'Represent hierarchies as trees of linked nodes, traverse them, and use binary search trees for ordered lookup.',
    details: `A tree has a root node, and every other node has exactly one parent and any number of children; nodes without children are leaves. Depth-first traversals visit a node before its children (preorder) or after them (postorder), and a binary tree adds an in-order traversal between its left and right subtrees. Breadth-first traversal visits level by level using a queue. Folder hierarchies, scene graphs, trees of coordinate frames and parsed expressions are all trees.

A binary search tree keeps smaller keys in the left subtree and larger keys in the right, so search and insertion follow one path from the root and cost time proportional to the tree's height. A balanced tree has a height of about log2 n, but inserting keys already in sorted order builds a tree that is effectively a linked list with linear-time lookup; self-balancing variants such as red-black trees prevent this. You can insert keys into a binary search tree by hand, list them with an in-order traversal and explain why sorted input ruins an unbalanced tree.` },
  { id: 'c-heaps', name: 'Priority queues and heaps', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'c-trees': 'A binary heap is a complete binary tree with an ordering rule.', 'c-arrays': 'A heap is stored compactly in an array using index arithmetic.' },
    helps: { 'm-search': 'A priority queue is what makes Dijkstra\'s shortest-path search efficient on large graphs.' },
    summary: 'Retrieve the smallest or most urgent item efficiently with a binary heap, the usual implementation of a priority queue.',
    details: `A priority queue supports two main operations: insert an item with a priority and remove the item with the best priority. A binary heap implements it as a complete binary tree stored in an array, where the children of index i sit at 2i + 1 and 2i + 2 and every parent is no larger than its children in a min-heap. Inserting places the item at the end and swaps it upward; removing the minimum moves the last item to the root and swaps it downward. Each takes time proportional to log n, while reading the minimum takes constant time.

A heap is not a sorted list: only the root is guaranteed to be the minimum. Shortest-path and A* search, event-driven simulation that always processes the next event in time, schedulers and "top k" queries all rely on this structure, available in Python as heapq. You can trace the array of a min-heap as 5, 3, 8 and 1 are inserted and explain why a heap beats keeping a sorted list for a long mix of inserts and removals.` },
  { id: 'c-graph-code', name: 'Graphs in code: representation and traversal', icon: 'tree', refs: ['MIT6006', 'CS2023'],
    after: { 'm-search': 'Graph search defines the traversals and shortest paths that this skill implements.', 'c-queues': 'Breadth-first search processes vertices from a queue.', 'c-hash-tables': 'Adjacency lists, visited sets, and parent maps are usually dictionaries and sets.' },
    helpedBy: { 'c-stacks': 'Depth-first search can be written with an explicit stack instead of recursion.', 'c-heaps': 'Dijkstra\'s algorithm and A* take the next vertex from a priority queue.' },
    summary: 'Store a graph as an adjacency list, matrix, or implicit grid, and implement searches that return the actual path, including Dijkstra\'s algorithm and A* with a priority queue.',
    details: `An adjacency list maps each vertex to its neighbours, often as a dictionary of lists that can also hold edge weights; it uses memory in proportion to vertices plus edges and suits sparse graphs such as road networks. An adjacency matrix answers "is there an edge from u to v?" in constant time but needs memory for every pair of vertices, so it suits small or dense graphs. Undirected edges are stored in both directions. Some graphs are implicit: the free cells of an occupancy grid are vertices whose neighbours are computed on demand instead of stored.

Code turns search into paths. Storing each vertex's parent when it is first reached lets the program walk back from the goal to rebuild the route, rather than only report that one exists. Weighted maps use Dijkstra's algorithm, which repeatedly takes the closest unsettled vertex from a priority queue, and A* adds an admissible heuristic, such as straight-line distance to the goal, so it expands fewer cells while still finding a shortest path. You can represent a 4-connected occupancy grid as an implicit graph, return the shortest path as a list of cells, and implement A* whose heuristic never overestimates the remaining cost.` },
  { id: 'c-searching', name: 'Linear and binary search', icon: 'code', refs: ['MIT6006', 'CS2023'],
    after: { 'c-arrays': 'Binary search depends on constant-time indexing into sorted data.', 'c-loops': 'Both searches are loops whose bounds and exit conditions must be exact.' },
    helpedBy: { 'm-log': 'The number of halvings binary search needs is a base-2 logarithm of the data size.' },
    summary: 'Find items by scanning, or by repeatedly halving a sorted range, and implement binary search without off-by-one errors.',
    details: `Linear search checks items one by one, works on any sequence and takes time proportional to its length. Binary search requires sorted data with fast indexing: it compares the target with the middle element and discards the half that cannot contain it, so a million sorted items need at most about 20 comparisons. The same idea finds the boundary in any monotonic yes-or-no question, such as the largest speed that stays within a stopping distance, or the sensor sample nearest a given timestamp.

Binary search is famously easy to get subtly wrong. You must keep a consistent convention for the bounds, for example inclusive low and exclusive high, make sure the range shrinks on every pass and, in fixed-width integer languages, compute the midpoint as low + (high - low) / 2 to avoid overflow. You can implement a version that returns the insertion position and test it on an empty array, a single element, a missing target and duplicates.` },
  { id: 'c-sorting', name: 'Sorting algorithms', icon: 'code', refs: ['MIT6006', 'CS2023'],
    after: { 'c-arrays': 'Sorting rearranges elements in indexed storage.', 'c-recursion': 'Merge sort and quicksort are recursive divide-and-conquer algorithms.' },
    helpedBy: { 'm-complexity': 'Comparing n squared with n log n sorting costs requires growth-rate notation.' },
    summary: 'Compare simple and efficient sorting algorithms by running time, memory, and stability, and use library sorts with custom keys.',
    details: `Insertion sort builds a sorted prefix one item at a time; it takes time proportional to n² in general but is fast on small or nearly sorted input. Merge sort splits the data in half, sorts each half recursively and merges them, taking n log n time and extra memory, and it is stable, keeping equal items in their original order. Quicksort partitions around a pivot and sorts in place, averaging n log n but degrading to n² with consistently bad pivots. Any algorithm that sorts only by comparing items needs about n log n comparisons in the worst case, although counting and radix sorts can do better for small integer keys.

In practice you call the built-in sort, such as Python's sorted() with a key function, and choose what to sort by. Stability matters when sorting by several keys in turn, for example by timestamp and then by sensor ID. You can trace merge sort on eight numbers, sort records by a computed key and explain why sorting once and then using binary search can beat repeated linear searches.` },
  { id: 'c-code-cost', name: 'Estimating the running time of code', icon: 'code', refs: ['MIT6006', 'CS2023'],
    after: { 'm-complexity': 'Growth-rate classes are the language used to state the estimate.', 'c-loops': 'Estimates come from counting how many times loops run.' },
    helpedBy: { 'c-hash-tables': 'Knowing which collection operations are constant time and which are linear reveals hidden costs inside loops.' },
    summary: 'Derive how a piece of code\'s time and memory grow with input size by counting loop iterations and the cost of the operations inside them.',
    details: `Growth rates become practical when you read them off code. A single pass over n items is linear, a loop inside a loop over the same items is quadratic and a loop that halves its range each time is logarithmic. The hidden costs sit inside loops: x in some_list scans the list, list.insert(0, x) shifts every element and building a long string by repeated concatenation can copy the text again and again. Memory counts too, including copies of data and the depth of recursion.

Asymptotic estimates ignore constant factors, which still matter for small inputs and on microcontrollers with tight time budgets, so estimates are checked by measuring with a profiler or timer at several input sizes. You can estimate the cost of a duplicate-finding function with nested loops, rewrite it with a set so it becomes linear and confirm the improvement by timing it at 1,000, 10,000 and 100,000 items.` },
  { id: 'c-numeric-arrays', name: 'Numerical arrays and vectorized computation', icon: 'matrix', refs: ['NUMPY', 'CS2023'],
    after: { 'c-arrays': 'Numerical arrays are typed, contiguous arrays, so indexing and storage costs carry over.' },
    helpedBy: { 'm-vector': 'Elementwise operations and broadcasting extend vector arithmetic to whole arrays.', 'm-matrix': 'The @ operator is matrix multiplication, which differs from elementwise multiplication.' },
    helps: { 'c-transforms': 'Transforming many points at once is a single matrix product on an N × 3 array.', 'c-features': 'Feature statistics are computed per column with axis-wise array operations.', 'c-neural-networks': 'A layer\'s forward pass over a batch of inputs is one array expression.' },
    summary: 'Compute on whole arrays at once with NumPy-style vectorized operations, slicing, broadcasting, and axis reductions instead of element-by-element loops.',
    details: `A NumPy array holds numbers of one type, such as float64 or uint8, in a contiguous block with a shape such as (1000, 3) for a thousand 3-D points. Arithmetic applies elementwise to whole arrays, so readings * 0.001 converts every value at once, far faster than a Python loop. Reductions take an axis: data.mean(axis=0) averages each column. Broadcasting stretches compatible shapes, compared from the rightmost dimension, where each pair of sizes must be equal or 1, so subtracting a (3,) mean from a (1000, 3) array centres every point. Boolean masks filter, as in ranges[ranges < 0.2], and the @ operator is matrix multiplication while * multiplies element by element.

Two behaviours surprise newcomers. Basic slicing returns a view, not a copy, so changing a slice changes the original array. Fixed-width types keep their limits, so in a uint8 array 250 + 10 wraps to 4, and precision depends on the chosen float type. You can compute per-axis statistics of an N × 3 IMU log without loops, transform N points with a single matrix product and predict whether two shapes broadcast or raise an error.` }
];
