// Computer architecture. Original descriptions; references are coverage checks only.
// Reuses existing atlas skills: m-binary (binary and hexadecimal) and the digital-logic skills
// e-mux, e-counter, and e-timing, which keep their Mathematics and Electronics domains.
export const subdomain = 'Computer architecture';
export const nodes = [
  { id: 'c-integers', name: 'Integer representation and overflow', icon: 'chip', refs: ['MIT6004', 'CS2023', 'WG14C'],
    after: { 'm-binary': 'Fixed-width integers are binary patterns, so place value in base 2 comes first.', 'm-sign': 'Two\'s complement encodes negative numbers, so signed arithmetic must be familiar.' },
    related: { 'e-counter': 'Hardware counters wrap from 2^N − 1 back to 0, which is where integer wraparound is met physically.' },
    summary: 'Represent signed integers in two\'s complement, state the range of a fixed-width integer, and recognize overflow and wraparound.',
    details: `N bits give 2^N patterns. Read as unsigned, they span 0 to 2^N − 1; read as two's complement, they span −2^(N−1) to 2^(N−1) − 1, so an 8-bit signed integer holds −128 to 127 and a 16-bit one holds −32,768 to 32,767. To negate a two's-complement value, invert every bit and add 1: −5 in 8 bits is 11111011. The same adder circuit handles signed and unsigned numbers; only the interpretation differs. Widening a signed value copies its top bit, so the 8-bit pattern 0xFF becomes −1, not 255.

When a result does not fit, it overflows. In C, unsigned arithmetic wraps modulo 2^N, while signed overflow is undefined behaviour that optimizing compilers may assume never happens. Python integers never overflow, which hides the issue until values are sent to a device. A 16-bit encoder counter wraps from 65,535 to 0, but taking the difference of two readings modulo 65,536 and reading it as signed still gives the correct small movement across the wrap. You can state the range of any fixed-width type, encode a negative number by hand and compute that wrap-safe difference.` },
  { id: 'c-floats', name: 'Floating-point numbers and rounding error', icon: 'chip', refs: ['PYTUT', 'MIT6004', 'CS2023'],
    after: { 'm-binary': 'A floating-point number stores its significand in binary.', 'm-power': 'The format is binary scientific notation, a significand times a power of two.' },
    helpedBy: { 'm-decimal': 'Rounding to a stated number of places is the decimal analogue of rounding to a fixed number of bits.' },
    related: { 'm-numerror': 'Roundoff from finite precision is one of the error sources that numerical error analysis tracks.' },
    summary: 'Explain how floating-point numbers store a sign, exponent, and significand, and handle their rounding error, limited precision, and special values.',
    details: `IEEE 754 floating-point numbers are binary scientific notation: a sign, a significand and a power of two. A 32-bit float has a 24-bit significand, about 7 significant decimal digits, and a 64-bit double has 53 bits, about 15 to 16 digits. Most decimal fractions, including 0.1, have no exact binary form, so 0.1 + 0.2 evaluates to 0.30000000000000004. Computed results are therefore compared within a tolerance rather than with ==, for example with math.isclose, whose default tolerance is relative, so comparisons against zero need an absolute tolerance (abs_tol).

Precision is relative, so the gap between neighbouring values grows with magnitude. A float32 clock counting seconds has a step of about 2 ms once it passes 16,384 s, roughly 4.5 hours, which is why long-running timestamps use doubles or integer ticks. Subtracting two nearly equal numbers cancels their accurate digits, and adding tiny increments to a large total can lose them entirely. Special values also propagate: inf, −inf and NaN, where NaN is not equal even to itself. You can explain a surprising float result, write tolerance comparisons and detect a NaN coming from a failed sensor calculation before it reaches a controller.` },
  { id: 'c-text-encoding', name: 'Character encoding: ASCII and UTF-8', icon: 'chip', refs: ['RFC3629', 'PYTUT', 'CS2023'],
    after: { 'm-binary': 'Encodings map characters to byte values written in binary and hexadecimal.', 'c-strings': 'Encoding is the boundary between string objects and stored or transmitted bytes.' },
    summary: 'Convert between text and bytes with an explicit encoding, and recognize ASCII, UTF-8, and the errors caused by mismatched encodings.',
    details: `Files, sockets and serial ports carry bytes, not characters; an encoding defines how characters become bytes. ASCII assigns 128 characters to the values 0 to 127, so "A" is 65 (0x41) and the digits "0" to "9" are 48 to 57, which is why ord(c) − ord("0") gives a digit's value. Unicode assigns a code point to every character, and UTF-8 stores ASCII characters as single bytes and all others as 2 to 4 bytes. "25°C" is therefore four characters but five bytes in UTF-8.

Decoding bytes with the wrong encoding produces either an error such as UnicodeDecodeError or silently garbled text. Python keeps bytes and str as separate types: data read from a serial port arrives as bytes and must be decoded, and text must be encoded before it is sent. Line endings differ too, with \\n on Linux and \\r\\n in many Windows files and serial protocols. You can count the bytes in a UTF-8 string, decode a device's reply correctly and diagnose garbled characters in a file.` },
  { id: 'c-bitwise', name: 'Bitwise operations and masks', icon: 'chip', refs: ['MIT6004', 'CS2023'],
    after: { 'm-binary': 'Masks and shifts are read and written in binary and hexadecimal.', 'm-logic': 'AND, OR, XOR, and NOT on bits follow the truth tables of logical operators, applied position by position.', 'c-expressions': 'Bitwise operators are expression operators with their own precedence.' },
    helpedBy: { 'm-boolean': 'Boolean identities such as De Morgan\'s laws simplify mask expressions.' },
    summary: 'Set, clear, toggle, test, and extract bit fields using AND, OR, XOR, NOT, and shifts.',
    details: `Bitwise operators work on every bit position at once: & (AND), | (OR), ^ (XOR), ~ (NOT) and the shifts << and >>. With a mask for bit 3, 1 << 3, you set the bit with x | (1 << 3), clear it with x & ~(1 << 3), toggle it with x ^ (1 << 3) and test it with (x >> 3) & 1. A multi-bit field is extracted by shifting it down and masking, so bits 4 to 6 are (x >> 4) & 0b111. Shifting an unsigned value left by n multiplies it by 2^n.

Hardware and data formats are full of such fields. A status register packs several flags into one byte, a 12-bit ADC result sent as two bytes is reassembled as (high << 4) | (low >> 4) when it is left-justified or as ((high & 0x0F) << 8) | low when right-justified, as the datasheet specifies, and a subnet mask selects the network part of an address with AND. Operator precedence is a common trap: in C, x & 1 == 0 compares before masking, so write (x & 1) == 0. You can decode which flags are set in a status byte, pack and unpack fields, and change one bit of a register without disturbing the others.` },
  { id: 'c-memory', name: 'Memory, addresses, and alignment', icon: 'memory', refs: ['MIT6004', 'CS2023'],
    after: { 'm-binary': 'Addresses are binary numbers, usually written in hexadecimal.', 'c-integers': 'The size of each integer type decides how many bytes it occupies.' },
    helpedBy: { 'c-arrays': 'Array indexing is the clearest example of computing an address from a base and an offset.' },
    summary: 'Model memory as numbered bytes, and relate addresses, word size, alignment, and the size of each data type.',
    details: `Main memory behaves like a huge array of bytes, each with a numeric address. A value larger than one byte occupies consecutive addresses: a 32-bit integer takes four. The address width limits how much memory can be named, so 32-bit addresses reach 4 GiB. A processor's word size, its natural register width, is typically 32 bits on microcontrollers and 64 bits on desktop computers, and it affects pointer size and how quickly values are handled.

Many processors require or prefer multi-byte values to be aligned, starting at an address that is a multiple of their size. Compilers therefore insert padding inside structures, so a C struct holding a uint8_t followed by a uint32_t normally occupies 8 bytes, not 5. On a microcontroller the memory map assigns address ranges to flash, RAM and peripheral registers, so an address alone tells you what kind of memory you are touching. You can compute the address of element i in an array of 32-bit integers, predict a structure's size and read a memory map.` },
  { id: 'c-byte-order', name: 'Byte order and binary data layouts', icon: 'memory', refs: ['MIT6004', 'RFC791', 'PYTUT'],
    after: { 'c-memory': 'Byte order describes how a multi-byte value is laid out in consecutive addresses.', 'c-integers': 'Decoding binary data means turning bytes back into signed or unsigned integers of a fixed width.' },
    helpedBy: { 'c-bitwise': 'Assembling a value from individual bytes uses shifts and OR.' },
    summary: 'Pack and unpack multi-byte values in a defined byte order and layout when exchanging binary data with files, devices, or networks.',
    details: `A multi-byte value can be stored with its least significant byte first, little-endian, as on x86 and most Arm systems, or its most significant byte first, big-endian, which is the conventional network byte order. The 16-bit value 0x1234 is the bytes 34 12 in little-endian and 12 34 in big-endian. Sensor datasheets state the order of their register bytes, and combining a high and low byte in the wrong order produces wildly wrong readings.

Portable binary formats are defined byte by byte rather than by copying a structure's memory, because padding, alignment and byte order differ between compilers and processors. Python's struct module and int.from_bytes() make the layout explicit, as in struct.unpack("<hH", data) or int.from_bytes(b"\\xff\\x38", "big", signed=True), which gives −200. Good formats also carry a length or version field so a reader can reject data it does not understand. You can decode a sensor's two-byte signed register and write the format string for a packet header from its specification.` },
  { id: 'c-registers', name: 'Processor registers and status flags', icon: 'chip', refs: ['MIT6004', 'ARMCM', 'CS2023'],
    after: { 'c-integers': 'The carry and overflow flags describe unsigned and signed overflow of integer results.', 'c-memory': 'Registers are understood in contrast to memory: they are few, fast, and not addressed like memory.' },
    helpedBy: { 'e-counter': 'A processor register is a bank of flip-flops, like the registers built in digital logic.' },
    summary: 'Describe the processor\'s registers, including general-purpose registers, the program counter, the stack pointer, and status flags, and say what each is used for.',
    details: `Registers are a small set of very fast storage locations inside the processor. In load-store architectures such as Arm and RISC-V, arithmetic works only on registers, so data is loaded from memory into registers, processed and stored back. A few registers have special jobs: the program counter holds the address of the next instruction, the stack pointer marks the top of the call stack and, on Arm, the link register holds a function's return address. An Arm Cortex-M core has registers R0 to R15, of which R13 to R15 are the stack pointer, link register and program counter, with the flags kept in a separate program status register; RISC-V has 32 integer registers, of which x0 always reads as zero.

Arithmetic also sets status flags that conditional branches test: N for a negative result, Z for zero, C for an unsigned carry out and V for signed overflow. Adding 0x7F and 0x01 in 8 bits gives 0x80, setting N and V but not C or Z. A calling convention states which registers carry function arguments and which must be preserved across calls. These core registers are distinct from peripheral registers, which are memory-mapped locations in devices. You can name the role of each special register and predict the flags after a small addition.` },
  { id: 'c-instructions', name: 'Machine instructions and assembly language', icon: 'chip', refs: ['MIT6004', 'CS2023'],
    after: { 'c-registers': 'Instructions name registers as their operands and update the program counter and flags.', 'c-loops': 'Reading assembly means recognizing the loops and conditions that compiled into branches.' },
    helpedBy: { 'c-build': 'Compilers produce this machine code, and reading their output shows what a line of source costs.' },
    summary: 'Read short assembly sequences and map loads, stores, arithmetic, comparisons, and branches back to the high-level code they implement.',
    details: `An instruction set architecture defines the operations a processor understands: moving data between registers and memory, arithmetic and logic, comparisons, conditional and unconditional branches, and calls and returns. Each instruction is encoded as binary machine code, and assembly language is its readable form, such as ADD r0, r0, #1 on Arm or addi t0, t0, 1 on RISC-V. Machine code for one architecture, such as x86-64, does not run on another, such as a Cortex-M microcontroller.

High-level code compiles into recognizable patterns. An if statement becomes a comparison followed by a conditional branch around a block, a loop becomes a branch backwards, and a function call saves a return address and jumps. Reading compiler output, for example in a disassembly or an online compiler explorer, shows what code really costs and why a variable read in a loop may be optimized away unless it is declared volatile. You can translate a loop that sums an array into pseudo-assembly with loads, adds, a compare and a branch, and explain why binaries are built per architecture.` },
  { id: 'c-processor', name: 'Processor datapath and pipelining', icon: 'chip', refs: ['MIT6004', 'CS2023'],
    after: { 'c-instructions': 'The datapath exists to carry out instructions, so the instruction set comes first.', 'e-mux': 'Control logic steers data through the datapath with multiplexers.', 'e-counter': 'The program counter and register file are clocked registers.' },
    related: { 'e-timing': 'The clock period is bounded by the slowest propagation path through the datapath, a digital timing constraint.' },
    summary: 'Trace how a processor fetches, decodes, and executes instructions through its datapath, and explain why pipelining raises throughput and what stalls it.',
    details: `A simple processor repeats one cycle: fetch the instruction at the program counter, decode it to find the operation and registers, execute it in the arithmetic logic unit, access memory for loads and stores, and write the result back to a register. Control signals set multiplexers that choose, for example, whether the ALU's second input comes from a register or from a constant in the instruction. In a single-cycle design the clock can tick no faster than the slowest instruction's path allows.

Pipelining overlaps these stages, like an assembly line, so several instructions are in progress at once and throughput approaches one instruction per clock. Dependencies cause hazards: an instruction that needs the result of the one just before it waits or receives the value by forwarding, and a mispredicted branch discards the work started behind it. Clock rate alone therefore does not measure performance; instructions per cycle and time spent waiting for memory matter as much. You can trace a load instruction through the five stages and explain why a mispredicted branch costs several cycles.` },
  { id: 'c-caches', name: 'Caches and memory locality', icon: 'memory', refs: ['MIT6004', 'OSTEP', 'CS2023'],
    after: { 'c-memory': 'Caches keep copies of memory contents, so the memory model comes first.', 'c-arrays': 'Locality is judged by how code walks through arrays and other data in memory.' },
    helpedBy: { 'c-processor': 'Cache misses matter because they stall the pipeline while data arrives.' },
    summary: 'Explain how caches exploit temporal and spatial locality, and write memory access patterns that run faster because of them.',
    details: `Memory is a hierarchy: registers, then level 1, 2 and sometimes 3 caches, then main memory, each level larger and slower. A load served from a level 1 cache takes a few cycles, while one that must go to main memory can take on the order of a hundred. Caches move data in fixed-size lines, 64 bytes on many desktop and application processors and 32 bytes on some microcontrollers such as the Cortex-M7, and many small microcontrollers have no data cache at all. Using data near something just used (spatial locality) and reusing recent data (temporal locality) therefore makes code fast.

Access order makes a large difference. Summing a big row-major matrix row by row walks through consecutive addresses and hits the cache, while going column by column jumps a whole row each time and misses constantly. Layout matters too: an array of structures versus a structure of arrays changes what a loop pulls into cache. On microcontrollers with caches and DMA, buffers must be cleaned or invalidated so the processor and the DMA controller see the same data. You can predict which of two loops is faster and restructure one for better locality.` },
  { id: 'c-io', name: 'Device input and output: polling, interrupts, and DMA', icon: 'chip', refs: ['MIT6004', 'OSTEP', 'CS2023'],
    after: { 'c-memory': 'Devices are controlled through registers placed at addresses in the memory map.', 'c-bitwise': 'Device registers are read and written one bit field at a time.' },
    summary: 'Explain how software controls devices through memory-mapped registers, and compare polling, interrupts, and DMA for moving data.',
    details: `Most devices expose control, status and data registers at fixed addresses. Writing a bit in a control register starts an action, and a status bit reports when it has finished or when data is ready. In C these registers are accessed through volatile pointers so the compiler performs every read and write instead of caching a value that the hardware can change on its own.

Software learns that a device needs attention in one of three ways. Polling repeatedly reads the status register: it is simple, but it wastes processor time, and its response time depends on how often the loop runs. An interrupt lets the device signal the processor, which runs a handler only when needed, which suits sporadic events. Direct memory access lets a controller copy whole blocks between a device and memory without the processor handling each byte, which suits streams such as continuous ADC sampling or display updates. You can choose between the three for a rare button press, a 1 kHz IMU and a fast ADC stream, and explain why a busy-wait for one serial byte blocks everything else.` }
];
