// Development practice. Original descriptions; references are coverage checks only.
export const subdomain = 'Development practice';
export const nodes = [
  { id: 'c-terminal', name: 'Terminal navigation and commands', icon: 'terminal', refs: ['MISSING', 'CS2023'],
    summary: 'Move around the file system from a command line, run programs with arguments, and read their output.',
    details: `A terminal runs a shell, a program that reads commands and runs them in a current working directory. pwd shows that directory (Get-Location in PowerShell), ls or dir lists it, and cd changes it. Paths are either absolute, starting from the root such as /home/ana or C:\\Users\\ana, or relative to where you are, where .. means the parent folder and ~ the home folder. Commands take arguments and options, as in python log_tool.py --rate 50 data.csv, and tab completion and command history save most of the typing.

When a command is not found, the shell could not locate it in the folders listed in the PATH variable. You have the skill when you can open a terminal, reach a project folder, create, copy and move files, run a script with arguments and explain why a relative path works from one directory but fails from another. Shell syntax differs between bash and PowerShell, so part of the skill is noticing which one you are in.` },
  { id: 'c-shell-pipes', name: 'Redirection, pipes, and exit codes', icon: 'terminal', refs: ['MISSING'],
    after: { 'c-terminal': 'Redirection and pipes combine commands that you must already be able to run from a shell.' },
    summary: 'Send a program\'s output to a file or to another program, and use exit codes to tell success from failure.',
    details: `Programs have a standard output stream for results and a standard error stream for diagnostics. > sends output to a file, replacing it, >> appends, and 2> captures errors separately. A pipe | feeds one program's output into the next, so a chain such as grep ERROR robot.log | sort | uniq -c counts each distinct error line. Every program also ends with an exit code: 0 means success and anything else means failure.

Scripts and automated builds depend on those codes. cmd1 && cmd2 runs the second command only if the first succeeded, and a script set to stop at the first failure avoids carrying on with missing results. You can capture a run to a log file, filter it for the lines you need, count them and make a script stop, with a clear message, when a step fails.` },
  { id: 'c-files', name: 'Reading and writing files', icon: 'code', refs: ['PYTUT', 'CS2023'],
    after: { 'c-strings': 'Text files are read and written as strings that must be split and formatted.', 'c-errors': 'Missing files and permission problems arrive as errors that must be handled.' },
    helpedBy: { 'c-terminal': 'Relative file paths resolve against the current working directory, which is a shell concept.' },
    summary: 'Open, read, write, and close text and structured data files with correct paths, modes, and encodings.',
    details: `A file is opened in a mode: "r" to read, "a" to append and "w" to write, which empties an existing file first. A with-block closes the file even if an error occurs. Large files are read line by line rather than all at once, and text files should be opened with an explicit encoding such as UTF-8. Libraries for CSV and JSON handle quoting and nesting correctly, so structured data is rarely parsed by hand.

Most file bugs are path bugs: a relative path is resolved from the current working directory, not from the folder containing the script, so a program that works from one folder fails from another. Building paths with pathlib or os.path avoids separator problems between Windows and Linux. For data that must not be lost, write to a temporary file and then swap it into place, with os.replace() in Python, which also works on Windows where a plain rename fails if the target exists, so a crash never leaves a half-written file. You can load a CSV of logged readings, compute a summary and write it out as JSON, handling a missing input file cleanly.` },
  { id: 'c-modules', name: 'Modules and imports', icon: 'code', refs: ['PYTUT', 'CS2023'],
    after: { 'c-functions': 'Modules exist to share functions and classes between files, so defining functions comes first.' },
    summary: 'Split a program across files, import names from modules, and understand how the language finds what you import.',
    details: `A module is a file of definitions that other code can import. import math makes math.sqrt available under the module's name, while from math import sqrt brings in just that name; the module name acts as a namespace that stops definitions from different files colliding. A package groups modules in a folder. In Python, the guard if __name__ == "__main__": lets one file work both as an importable module and as a runnable script.

Imports are resolved by searching a list of locations: the project, then installed packages. Naming your own file random.py or serial.py therefore hides the real library, and two modules that import each other at the top level can fail with confusing partial-initialization errors. You can reorganize a long script into a small package with a clear entry point and diagnose a ModuleNotFoundError.` },
  { id: 'c-dependencies', name: 'Package dependencies and environments', icon: 'terminal', refs: ['PYTUT', 'MISSING', 'CS2023'],
    after: { 'c-modules': 'Installed packages are used through imports.', 'c-terminal': 'Package managers and environments are driven from the command line.' },
    summary: 'Install third-party packages into an isolated environment and record exact versions so the project can be rebuilt elsewhere.',
    details: `Package managers such as pip, npm and apt download libraries and the libraries those depend on. An isolated environment, such as a Python virtual environment created with python -m venv, keeps each project's packages separate, so upgrading one project cannot break another. A dependency file such as requirements.txt, pyproject.toml or package.json declares what the project needs, and a lock file records the exact versions actually installed, including indirect dependencies.

"It works on my machine" usually means different package versions. Version ranges follow semantic versioning in many ecosystems, where a change in the first number signals a breaking change, but pinned versions are what make a build reproducible for a robot that must run the same software for months. Every dependency is also code you trust, so install from official sources and add packages deliberately. You can create an environment, install pinned dependencies and rebuild the same environment on another computer from the files in the repository.` },
  { id: 'c-build', name: 'Compilation, linking, and build tools', icon: 'terminal', refs: ['MISSING', 'CS2023'],
    after: { 'c-c-language': 'The build steps and error messages are those of compiling C source files and headers.', 'c-modules': 'Builds combine code split across several files, the idea modules introduce.' },
    summary: 'Explain how source files become an executable through compiling and linking, and drive that process with a build tool.',
    details: `In compiled languages such as C, C++ and Rust, a compiler translates each source file into object code for a particular processor, and a linker combines the object files and libraries into one executable, connecting each call to its definition. The two stages fail differently: a missing semicolon is a compiler error, while "undefined reference to motor_init" means the linker could not find a definition that some file promised through a header declaration.

Build tools such as make and CMake, or colcon for ROS 2 workspaces, record which outputs depend on which inputs and rebuild only what changed. Debug builds keep symbols for debugging, while release builds optimize and may behave differently if the code relies on undefined behaviour. Cross-compiling uses a toolchain for another processor, such as a microcontroller, rather than the computer doing the build. You can build a two-file C program by hand, then with a build file, and say whether a given error came from the compiler or the linker.` },
  { id: 'c-debugging', name: 'Systematic debugging', icon: 'code', refs: ['MISSING', 'CS2023'],
    after: { 'c-errors': 'Debugging starts by reading error messages and tracebacks correctly.', 'c-functions': 'Isolating a fault means checking the inputs and outputs of individual functions.' },
    summary: 'Find the cause of a bug by reproducing it, narrowing down where it occurs, and testing one hypothesis at a time.',
    details: `Effective debugging is a search, not a sequence of random edits. First make the bug happen reliably with the smallest input that shows it. Read the whole error message and traceback, then compare what the program should hold with what it actually holds at intermediate points, using temporary prints, logs or a debugger. Halve the search space repeatedly, whether that is the code path, the input data or the project history, where git bisect finds the commit that introduced a fault.

Change one thing at a time and fix the cause rather than the symptom: clamping a negative distance hides the sign error that produced it. Timing-related bugs may vanish when you add prints, which is itself a clue. When the bug is found, add a test that fails without the fix. You can take a function that returns a wrong average for some inputs, identify the class of failing inputs and name the responsible line without guessing.` },
  { id: 'c-debugger', name: 'Using an interactive debugger', icon: 'terminal', refs: ['MISSING'],
    after: { 'c-debugging': 'A debugger is a tool for the hypothesis-driven search that systematic debugging describes.' },
    summary: 'Pause a running program at breakpoints, step through it, and inspect variables and the call stack.',
    details: `A debugger runs a program under control. A breakpoint pauses execution at a chosen line, and a conditional breakpoint pauses only when an expression is true, for example when speed < 0. From there you can step over the next line, step into a call or step out of the current function, inspect and evaluate variables, and move up the call stack to see which caller passed a bad value. Post-mortem debugging opens the state at the moment an exception occurred. Tools include pdb and IDE debuggers for Python, and gdb for C and C++, which on microcontrollers connects through a hardware probe.

A debugger beats print statements when the state is complex or the path to a failure is unknown. It is less suitable for timing-sensitive code: pausing a control loop halts the controller while motors may keep their last command, so real-time faults are often better investigated with logging and trace tools. You can set a conditional breakpoint, walk up the stack to the origin of a bad value and explain when pausing would change the behaviour under test.` },
  { id: 'c-testing', name: 'Unit testing', icon: 'code', refs: ['PYUNITTEST', 'CS2023', 'MISSING'],
    after: { 'c-functions': 'A unit test calls a function with known inputs and checks its result.', 'c-errors': 'Tests must check that invalid input raises the intended error.' },
    summary: 'Write automated tests that check a function\'s results, including edge cases, and run them to catch regressions.',
    details: `A unit test is a small automated program that calls one unit of code with known inputs and asserts the expected result. A test runner such as pytest, unittest or node:test finds the tests, runs them and reports which failed and why. Good test cases cover the typical case, the boundaries such as zero, empty lists and maximum values, and invalid input that should raise an error. Floating-point results are compared within a tolerance rather than for exact equality.

Tests are only useful if they are independent and repeatable: no reliance on test order, the current time or real hardware unless that is the point. Code that talks to devices is easier to test when the hardware access sits behind a small interface that a test can replace with a fake. A test that fails before a bug fix and passes after it guards against that bug returning. You can write tests for a function that converts encoder counts to distance, including negative counts and counter wraparound, and watch a test fail when you introduce a deliberate bug.` },
  { id: 'c-git-commits', name: 'Version control with Git commits', icon: 'branch', refs: ['PROGIT', 'MISSING', 'CS2023'],
    after: { 'c-terminal': 'Git is used through commands in a terminal, or through tools that expose the same commands.' },
    summary: 'Record project history as commits, inspect what changed, and restore earlier versions of files.',
    details: `Git tracks a project folder called a repository. Changes move from the working tree into the staging area with git add, and git commit records a snapshot with a message and a link to its parent commit, building a history. git status shows what has changed, git diff shows the changed lines, git log lists history, and git restore discards unstaged edits to a file, returning it to the staged version, or to the last commit with --source=HEAD. A .gitignore file keeps generated files, large data and secrets out of the repository.

Commits are most useful when each contains one logical change, and its message says why the change was made, not just which file was touched. Anything committed is easy to share and hard to erase completely, so passwords and access tokens must never be committed. You can make several edits, commit only some of them, compare two commits and recover a file you deleted or broke.` },
  { id: 'c-git-branches', name: 'Git branches and merging', icon: 'branch', refs: ['PROGIT', 'MISSING'],
    after: { 'c-git-commits': 'A branch is a named pointer to a commit, so commits and history come first.' },
    related: { 'm-dag': 'Git history is a directed acyclic graph of commits, in which a merge commit has two parents.' },
    summary: 'Develop changes on separate branches, merge them back, and resolve conflicts when two branches edit the same lines.',
    details: `A branch is a movable name that points at a commit, and HEAD marks the branch you are working on. git switch -c feature creates a branch, so experimental work stays separate from the stable main branch. Merging brings the work back: if main has not moved on, Git simply fast-forwards the pointer, and otherwise it creates a merge commit with two parents. Rebasing instead replays commits onto a new base, rewriting their history, so it should not be used on commits that other people already have.

When both branches change the same lines, Git stops and marks the conflict in the file between <<<<<<< and >>>>>>> lines. Resolving it means deciding what the combined code should be, not just deleting one side, and then running the tests before committing. You can create two branches that edit the same line, merge them, resolve the conflict and read the result with git log --graph.` },
  { id: 'c-git-remotes', name: 'Remote repositories and pull requests', icon: 'branch', refs: ['PROGIT', 'CS2023'],
    after: { 'c-git-branches': 'Collaboration happens by pushing branches and merging them through review.' },
    summary: 'Clone, fetch, pull, and push to shared repositories, and propose changes through reviewed pull requests.',
    details: `A remote is another copy of the repository, usually on a server and named origin. git clone copies it, git fetch downloads new commits without changing your work, git pull fetches and then merges or rebases, and git push uploads your branch. A push is rejected when the remote has commits you do not have, and the correct response is to fetch and integrate them, not to force-push over other people's work.

Most teams propose changes through pull requests, called merge requests on some platforms: push a branch, open a request describing what changed and how it was tested, let automated checks run, answer review comments and then merge. Access uses SSH keys or tokens stored in a credential manager, never pasted into code or chat. You can contribute a change to a shared repository through a pull request, handle a rejected push and bring your branch up to date with main.` },
  { id: 'c-documentation', name: 'Documenting code and projects', icon: 'code', refs: ['PEP257', 'PYUNITTEST', 'MISSING'],
    after: { 'c-functions': 'Docstrings and interface notes describe functions: their parameters, results, and errors.' },
    summary: 'Write comments, docstrings, and README files that let another person, or you later, use and change the code correctly.',
    details: `Documentation works at three levels. Comments explain why the code does something non-obvious, such as a workaround for a sensor quirk; they should not restate what the code plainly does. Docstrings describe a function's purpose, parameters, return value and errors, including units and conventions, for example "angle in radians, positive counter-clockwise about +z". A README tells a newcomer what the project is and how to install, run and test it.

Out-of-date documentation misleads more than missing documentation, so it belongs next to the code and changes in the same commit as the behaviour it describes. Short, runnable examples are often worth more than paragraphs. You can hand your project to someone who has never seen it, and they can set it up and run it from the README alone, and every public function states its units and what happens on bad input.` },
  { id: 'c-linux-admin', name: 'Remote Linux administration: SSH, permissions, and services', icon: 'terminal', refs: ['MISSING', 'OPENSSH', 'SYSTEMD'],
    after: { 'c-terminal': 'Administration is done from a shell, locally or over SSH.', 'c-processes': 'A service is a process that the service manager starts, restarts, and logs.' },
    summary: 'Work on a Linux robot computer remotely over SSH, manage file permissions and administrator access, and run software as a service that starts at boot.',
    details: `Robot computers are usually headless and reached over the network. ssh user@robot.local opens a remote shell, key pairs made with ssh-keygen and installed on the robot replace passwords, and scp or rsync copy files across. Linux permissions give read, write and execute rights to a file's owner, its group and everyone else: chmod +x makes a script executable, and sudo runs one command with administrator rights. A classic robotics failure is "permission denied" on /dev/ttyUSB0, which is fixed by adding the user to the group that owns the device, often dialout, not by running everything as root.

Software that must start at boot and restart after a crash runs as a service. With systemd, a unit file names the command, the user, the working directory and the restart policy; systemctl starts, stops and enables the service, and journalctl shows its logs. A service does not inherit your interactive shell's environment, so paths and environment variables are set in the unit file. You can set up key-based SSH to a robot, fix a serial-port permission error properly and turn a program into a service that starts at boot, restarts on failure and leaves logs you can read.` }
];
