// Embedded and real-time computing. Original descriptions; references are coverage checks only.
// Reuses existing Electronics skills (e-bus, e-counter, e-logicvoltage, e-pwm) without reclassifying them.
export const subdomain = 'Embedded and real-time';
export const nodes = [
  { id: 'c-microcontrollers', name: 'Microcontroller architecture', icon: 'chip', refs: ['RP2040DS', 'CMSIS', 'CS2023'],
    after: { 'c-memory': 'A microcontroller is described by its memory map of flash, RAM, and peripherals.', 'c-io': 'Its peripherals are controlled through memory-mapped registers.' },
    helpedBy: { 'c-processor': 'Knowing how a processor core executes instructions explains clock speed and core choices.' },
    summary: 'Describe what a microcontroller integrates, including core, flash, RAM, clocks, and peripherals, and choose one against a project\'s needs.',
    details: `A microcontroller puts a processor core, such as an Arm Cortex-M0+ or M4 or a RISC-V core, on one chip together with flash memory for the program, a small RAM measured in kilobytes, clock generation and peripherals: GPIO, timers, ADCs, UART, SPI and I²C controllers, PWM generators and DMA. It runs a single program straight from reset, with no operating system or only a small real-time one. Each peripheral is controlled through registers described in the chip's reference manual, while the datasheet gives electrical limits and pin functions; most pins can take one of several functions, chosen in software.

Compared with a single-board computer running Linux, a microcontroller boots in milliseconds, uses little power and gives predictable timing, while the computer offers far more processing power, memory and ready-made software. Many robots use both: microcontrollers for motor control and sensor timing, a computer for perception and planning. You can read a datasheet to find flash and RAM size, the number of UARTs, ADC resolution and which pins can produce PWM, and justify a choice between a microcontroller and a Linux computer for a given task.` },
  { id: 'c-firmware', name: 'Firmware structure, build, and flashing', icon: 'chip', refs: ['PICOSDK', 'ZEPHYR', 'CMSIS'],
    after: { 'c-microcontrollers': 'Firmware is written for a particular microcontroller and its memory map.', 'c-build': 'Firmware is produced with a cross-compiling toolchain and a build system.', 'c-loops': 'The main program is an endless loop.' },
    summary: 'Build firmware with a cross-toolchain, flash it onto a microcontroller, and structure it as startup code, initialization, and a main loop.',
    details: `After reset, a Cortex-M core loads its stack pointer and the address of the reset handler from a vector table. Startup code then copies initialized variables from flash to RAM, zeroes the zero-initialized ones (the .bss section), configures the clocks and calls main. Firmware main never returns: it initializes the peripherals and then loops forever, typically reading inputs, updating state and writing outputs on every pass. A linker script decides where code and data go in flash and RAM.

The build uses a cross-compiler such as arm-none-eabi-gcc, driven by CMake, the Pico SDK or Zephyr's west tool, and produces an ELF file plus a binary or UF2 image. Flashing is done through a USB bootloader, for example by copying a UF2 file to a board that appears as a drive, or through a debug probe over SWD or JTAG, which also allows stepping through code. Vendor HAL and SDK libraries hide register details; frameworks such as Arduino hide more. You can build and flash a blinking-LED program, explain what happens before main runs and recover a board whose firmware hangs at startup by entering its bootloader.` },
  { id: 'c-gpio', name: 'GPIO configuration and digital I/O', icon: 'chip', refs: ['PICOSDK', 'RP2040DS', 'ZEPHYR'],
    after: { 'c-firmware': 'Pins are configured and used by firmware running on the microcontroller.' },
    helpedBy: { 'c-bitwise': 'Direct register access sets and clears individual pin bits with masks.', 'e-logicvoltage': 'Input voltage thresholds decide which voltages a pin reads as 0 or 1.' },
    summary: 'Configure general-purpose pins as inputs or outputs with suitable pull resistors and drive modes, read and write them, and debounce mechanical inputs.',
    details: `Each GPIO pin is set to a function, either plain GPIO or a peripheral such as a UART, and, as GPIO, to input or output. An unconnected input floats and reads random values, so inputs use an internal or external pull-up or pull-down resistor. A button wired to ground with a pull-up reads 1 when released and 0 when pressed, which is called active low. A push-pull output actively drives both high and low, while an open-drain output only pulls low and relies on a pull-up for high, which lets several devices share one line and, if the pin tolerates the pulled-up voltage, connects to a different logic level.

Pins source or sink only a few milliamps, so motors and relays need a driver transistor and LEDs need a current-limiting resistor, and a 3.3 V microcontroller pin may not tolerate 5 V. Mechanical switches bounce for a few milliseconds, producing several edges per press, so firmware debounces by requiring a stable reading for 10 to 20 ms or by ignoring edges for a short time after the first. You can configure and debounce a button input, explain why a floating input toggles on its own and choose open-drain for a shared fault line.` },
  { id: 'c-interrupts', name: 'Interrupts and interrupt service routines', icon: 'chip', refs: ['ARMCM', 'MIT6004', 'CS2023'],
    after: { 'c-firmware': 'Interrupt handlers are part of firmware and are registered in its vector table.', 'c-io': 'Interrupts are how devices signal the processor instead of being polled.' },
    helpedBy: { 'c-race-conditions': 'Data shared between an interrupt handler and the main loop has the same lost-update hazards as data shared between threads.' },
    helps: { 'c-os-scheduling': 'A periodic timer interrupt is what lets an operating system preempt a running thread.' },
    summary: 'Configure interrupts, write short interrupt service routines, and share data safely between an ISR and the main program.',
    details: `An interrupt makes the processor pause the current code, save its context and run an interrupt service routine (ISR) found through the vector table, then resume. Pin edges, timer overflows, received UART bytes and completed ADC conversions are typical sources. An interrupt must be enabled both in the peripheral and in the interrupt controller, the NVIC on Cortex-M, where a lower priority number means a more urgent interrupt. The ISR must clear the peripheral's pending flag, or the interrupt fires again immediately and the system appears to freeze.

ISRs should be short: record a timestamp, set a flag or move a byte into a ring buffer, and leave heavy work to the main loop. They must never block or call slow functions such as printf. Variables shared with the main loop are declared volatile so the compiler rereads them, and values wider than one atomic access, such as a 64-bit counter on a 32-bit core, are read inside a brief critical section with interrupts disabled. You can count encoder edges in an ISR, read the count in the main loop without tearing and measure an ISR's duration by toggling a pin during it.` },
  { id: 'c-timers', name: 'Hardware timers and PWM generation', icon: 'clock', refs: ['RP2040DS', 'PICOSDK', 'ZEPHYR'],
    after: { 'c-firmware': 'Timers are peripherals configured and used by firmware.' },
    helpedBy: { 'e-counter': 'A hardware timer has the structure of the clocked counters built in digital logic, with a prescaler, compare values, and wraparound added.' },
    related: { 'e-pwm': 'Pulse-width modulation\'s electrical effect on a motor or LED is the electronics side of the waveform a timer generates.' },
    summary: 'Configure hardware timers from clock, prescaler, and period to produce periodic interrupts and PWM outputs and to measure time precisely.',
    details: `A hardware timer is a counter driven by the system clock through a prescaler, or divider. It counts up to a wrap or reload value, restarts and can raise an interrupt each time, so the period is prescaler × (wrap + 1) / clock frequency. With a 100 MHz clock, a divider of 100 gives a 1 MHz tick, and a wrap value of 999 then gives a 1 kHz interrupt. A compare channel switches an output pin when the count passes a set value, producing PWM whose duty cycle is compare / (wrap + 1). Input capture records the count at the moment an input pin changes, which measures pulse widths or the time between encoder edges.

Choosing the divider and wrap value trades resolution against range: a 20 kHz PWM from a 100 MHz clock with 1,000 duty steps needs a divider of 5, while a finer 5,000 steps needs a divider of 1. A free-running microsecond counter provides timestamps, but a 32-bit microsecond counter wraps after about 71 minutes, so differences must be computed wrap-safely. You can calculate timer settings for a required frequency and resolution, generate a periodic interrupt and measure a pulse width with input capture.` },
  { id: 'c-serial-drivers', name: 'UART, SPI, and I²C in firmware', icon: 'chip', refs: ['NXPI2C', 'ADISPI', 'ADIUART', 'PICOSDK'],
    after: { 'e-bus': 'Driving these buses from firmware builds on knowing how their clocking, wiring, and addressing differ.', 'c-firmware': 'The bus controllers are peripherals configured by firmware.', 'c-byte-order': 'Sensor registers deliver multi-byte values in a stated byte order.' },
    helpedBy: { 'c-queues': 'Interrupt-driven receive code stores incoming bytes in a ring buffer.' },
    summary: 'Configure UART, SPI, and I²C peripherals and use them from firmware to exchange data with sensors and other chips.',
    details: `Each bus has its own firmware routine. A UART needs a baud rate and frame format, usually 8 data bits, no parity and 1 stop bit, identical on both ends; received bytes are best moved into a ring buffer by an interrupt, or incoming data is overrun and lost while the program is busy. SPI needs the clock polarity and phase (the SPI mode) and speed from the device's datasheet, and the chip select held active for the whole transaction; every byte sent clocks one byte back in. I²C addresses a device by its 7-bit address, usually writes a register number and then reads with a repeated start, and each byte is acknowledged: a NACK means a wrong address, a missing device or a device that is busy.

Bring-up starts by reading a known identification register, often called WHO_AM_I, before trusting any data. A logic analyzer that decodes the bus shows exactly which bytes were sent and whether they were acknowledged. Buses can also get stuck, for example an I²C device holding the data line low after a reset mid-transfer, which firmware clears by clocking the bus until the line is released. You can read a sensor's ID register over I²C and handle a NACK, set the SPI mode from a timing diagram and receive UART data at 115,200 baud without losing bytes.` },
  { id: 'c-fixed-point', name: 'Fixed-point arithmetic', icon: 'chip', refs: ['CS2023', 'CMSIS'],
    after: { 'c-integers': 'Fixed-point values are integers with an agreed scale, so integer ranges and overflow come first.', 'c-bitwise': 'Rescaling by powers of two is done with shifts.' },
    helpedBy: { 'c-floats': 'Comparing with floating point shows what fixed point gives up in range and gains in speed and determinism.' },
    summary: 'Represent fractional values as scaled integers, choose a Q format, and add, multiply, and round them without overflow.',
    details: `A fixed-point number stores a real value x as the integer round(x × 2^n), where n is the number of fractional bits. The Q15 format keeps values from −1 to just under 1 in an int16 with n = 15, so 0.75 is stored as 24,576. Numbers with the same scale can be added directly. A product has 2n fractional bits, so two Q15 values are multiplied in 32 bits and shifted right by 15, ideally adding 2^14 first to round rather than truncate. Decimal scales work too, such as millivolts or hundredths of a degree held in integers.

The scale is chosen from the range and resolution a value needs. Overflow must be prevented by widening intermediate results or handled by saturating, clamping to the largest value rather than wrapping around, which is essential for controller outputs, where a wrap turns full forward into full reverse. Fixed point matters on microcontrollers without a floating-point unit and for bit-exact, repeatable results, and the same ideas underlie int8 quantized neural networks. You can convert values to and from Q15, multiply them correctly and choose an integer scale for a PID gain.` },
  { id: 'c-watchdog', name: 'Watchdog timers and fail-safe states', icon: 'clock', refs: ['RP2040DS', 'ZEPHYR'],
    after: { 'c-firmware': 'The watchdog is fed, and reset causes are handled, by the firmware\'s main loop and startup code.' },
    helpedBy: { 'c-timers': 'A watchdog is an independent timer that resets the chip when it expires.', 'c-interrupts': 'Knowing what keeps running when the main loop hangs shows where the watchdog must and must not be fed.' },
    summary: 'Use a watchdog timer to recover from hung firmware, and design reset and communication-loss paths so outputs fall to a safe state.',
    details: `A watchdog is an independent timer that resets the microcontroller unless the software feeds, or kicks, it before it expires. It should be fed only when the whole system has shown it is healthy, for example at the end of a main-loop pass in which every task ran. Feeding it from a timer interrupt defeats it, because interrupts often keep running after the main loop has hung. After any reset, firmware should read the reset-cause register, record why it restarted and start with outputs in a safe condition.

Safe states are designed, not assumed: a motor driver's enable pin can have a pull-down resistor so the driver stays off while the microcontroller is resetting and its pins float. The same idea applies to communication: if no valid command has arrived within, say, 200 ms, the firmware stops the motors, a so-called heartbeat or deadman timeout. Brown-out detection resets the chip cleanly when the supply sags instead of letting it run erratically. You can explain why feeding a watchdog from an interrupt is a mistake, implement a command timeout that stops a robot when its link drops and read the reset cause at boot.` },
  { id: 'c-timing-constraints', name: 'Deadlines, jitter, and execution-time budgets', icon: 'clock', refs: ['LL73', 'CS2023', 'FREERTOS'],
    after: { 'c-timers': 'Periods and time measurements come from hardware timers.', 'c-interrupts': 'Interrupt load and latency consume part of every timing budget.' },
    helpedBy: { 'c-latency': 'Latency and jitter are the same quantities whether they arise in a network or inside one controller.', 'c-code-cost': 'Estimating how code scales predicts which inputs produce the worst-case execution time.' },
    summary: 'State a task\'s timing requirements as periods and deadlines, measure execution time and jitter, and check that the worst case fits the budget.',
    details: `A real-time system is correct only if its results arrive on time. A task has a period, a deadline and an execution time; a hard deadline must never be missed, a firm one makes a late result worthless, and a soft one degrades quality when missed. Jitter is the variation in when a task starts or finishes. What matters is the worst-case execution time, not the average: cache misses, interrupts, rarely taken branches, heap allocation and logging all add occasional long runs. Utilization, the sum of each task's execution time divided by its period, gives a first check on whether the processor is overloaded.

Execution time is measured, not guessed: toggle a GPIO pin at the start and end of the code and watch it on an oscilloscope or logic analyzer, or read a cycle counter, and record the maximum over a long run under realistic load. A 1 kHz control loop has 1 ms for everything, including sensor reads, computation, output and the interrupts that pre-empt it. You can measure a control step's minimum, mean and maximum duration, judge whether a 0.7 ms worst case plus 0.2 ms of interrupt load fits a 1 kHz loop and track down the cause of an occasional overrun.` },
  { id: 'c-rt-scheduling', name: 'Real-time scheduling and priority inversion', icon: 'clock', refs: ['LL73', 'FREERTOS', 'OSTEP'],
    after: { 'c-timing-constraints': 'Schedulability is judged from each task\'s period, deadline, and worst-case execution time.', 'c-os-scheduling': 'Real-time scheduling specializes preemptive priority scheduling.', 'c-synchronization': 'Priority inversion arises when tasks of different priorities share a lock.' },
    summary: 'Assign task priorities by rate-monotonic or deadline rules, check whether a task set can meet its deadlines, and prevent priority inversion.',
    details: `Most real-time kernels use fixed-priority preemptive scheduling: the highest-priority ready task always runs. Rate-monotonic assignment gives higher priority to tasks with shorter periods, which is optimal among fixed-priority schemes for independent periodic tasks whose deadlines equal their periods. Liu and Layland's test guarantees schedulability if total utilization is at most n(2^(1/n) − 1), about 0.78 for three tasks and approaching 0.69 for many; this is sufficient but not necessary, and exact response-time analysis can accept task sets above it. Earliest-deadline-first scheduling changes priorities dynamically and, under the same assumptions, meets all deadlines up to full utilization.

Priority inversion happens when a low-priority task holds a lock that a high-priority task needs and a medium-priority task pre-empts the low one, leaving the high-priority task waiting for an unbounded time; this famously reset the Mars Pathfinder lander in 1997. Mutexes with priority inheritance, which temporarily raise the lock holder's priority, and short critical sections prevent it; in FreeRTOS, mutexes have priority inheritance and binary semaphores do not. You can assign rate-monotonic priorities to three tasks, check them against the bound and draw an inversion timeline, showing how inheritance ends it.` },
  { id: 'c-rtos', name: 'RTOS tasks, queues, and timers', icon: 'clock', refs: ['FREERTOS', 'ZEPHYR'],
    after: { 'c-firmware': 'An RTOS runs inside firmware on the microcontroller.', 'c-synchronization': 'RTOS tasks coordinate through mutexes, semaphores, and queues.', 'c-os-scheduling': 'The RTOS kernel is a small preemptive priority scheduler.' },
    helpedBy: { 'c-rt-scheduling': 'Priority assignment rules decide how tasks should be ranked.' },
    summary: 'Structure firmware as prioritized tasks under a real-time operating system, communicating through queues, semaphores, and software timers.',
    details: `A real-time operating system such as FreeRTOS or Zephyr lets firmware run several tasks, each with its own stack and priority, under a preemptive scheduler. Tasks block when they have nothing to do, waiting on a delay, a queue or a semaphore, which lets lower-priority tasks run instead of wasting the processor in busy loops. Queues copy data between tasks and from interrupt handlers, which must use the special interrupt-safe calls, such as FreeRTOS's FromISR functions. Software timers run short callbacks at set times, and a delay until the next period, as with xTaskDelayUntil (vTaskDelayUntil before FreeRTOS 10.4), keeps a periodic task from drifting the way a plain delay does.

Each task's stack must be sized for its deepest call chain, with the kernel's overflow checks enabled during development. An RTOS pays off when a device has several activities with different rates and deadlines, such as sampling a sensor at 1 kHz, running control at 500 Hz and handling communication, but it costs RAM and adds concurrency hazards compared with a single main loop. You can divide robot firmware into sensor, control and communication tasks with justified priorities, pass samples from an interrupt to a task through a queue and make a periodic task run without drift.` }
];
