// Networking. Original descriptions; references are coverage checks only.
export const subdomain = 'Networking';
export const nodes = [
  { id: 'c-packets', name: 'Packets, headers, and protocol layers', icon: 'network', refs: ['RFC791', 'CS2023'],
    after: { 'm-binary': 'Header fields are fixed numbers of bits and bytes, read in binary and hexadecimal.' },
    helpedBy: { 'c-byte-order': 'Multi-byte header fields are sent in network byte order.' },
    summary: 'Describe how data travels as packets whose headers carry addressing and control information, and how protocol layers wrap one another.',
    details: `Networks move data in packets rather than as one continuous stream. Each protocol layer adds its own header in front of the data it carries: application data sits inside a TCP or UDP segment, which sits inside an IP packet, which sits inside an Ethernet or Wi-Fi frame. This wrapping is called encapsulation. Headers hold the information each layer needs, such as source and destination addresses, lengths, a number identifying the next protocol and a checksum.

Routers forward each IP packet independently toward its destination address, so packets can be lost, duplicated, delayed or arrive out of order. A link also limits packet size, typically about 1,500 bytes of IP packet on Ethernet, so a larger message is split across several packets. Layering lets one part change without the others: the same TCP connection works over Wi-Fi or a cable. You can label the layers and main header fields in a packet capture, say which header a router reads and explain why a 4 kB message becomes several packets.` },
  { id: 'c-ip-addressing', name: 'IP addresses, subnets, and ports', icon: 'network', refs: ['RFC791', 'RFC4632', 'CS2023'],
    after: { 'c-bitwise': 'Deciding whether two addresses share a subnet is a bitwise AND with the mask.', 'c-packets': 'Addresses are fields in the packet header that routers use for forwarding.' },
    summary: 'Read IPv4 and IPv6 addresses with prefix lengths, decide whether two hosts share a subnet, and use port numbers to reach a program on a host.',
    details: `An IPv4 address is 32 bits, written as four decimal bytes such as 192.168.1.20. A prefix length such as /24 says how many leading bits identify the network, leaving 8 bits for hosts: 256 addresses, of which 254 are normally usable because the all-zeros and all-ones host addresses are reserved. Two hosts are on the same subnet when their addresses match after masking with the prefix; otherwise traffic goes through a router, the default gateway. Private ranges such as 192.168.0.0/16 and 10.0.0.0/8 are reused behind network address translation, 127.0.0.1 is the machine itself, and IPv6 uses 128-bit addresses written in hexadecimal groups.

Addresses are usually assigned automatically by DHCP, and DNS translates names into addresses. A 16-bit port number selects the program on the host, so a service is reached at an address, a port and a protocol. Many robot networking problems are addressing problems: a laptop on a different subnet from the robot, or a server bound to 127.0.0.1 that no other computer can reach. You can tell whether 192.168.1.20/24 and 192.168.2.5 share a subnet, find the network address of 10.0.5.77/16 and explain the loopback problem.` },
  { id: 'c-checksums', name: 'Error detection with checksums and CRCs', icon: 'network', refs: ['RFC791', 'RFC9293', 'CS2023'],
    after: { 'm-binary': 'Check values are computed over bits and bytes.', 'c-bitwise': 'Parity, checksums, and CRCs are computed with XOR, shifts, and masks.' },
    helpedBy: { 'm-modular': 'Checksums use sums reduced by a modulus, and CRCs are remainders of polynomial division over bits.' },
    summary: 'Detect corrupted data with parity bits, checksums, and cyclic redundancy checks, and know what each can and cannot catch.',
    details: `Electrical noise and radio interference flip bits. To detect this, a sender computes a short check value from the data and sends it along; the receiver recomputes it and discards the data if they disagree. A parity bit catches any single flipped bit but misses two. The Internet checksum, a ones' complement sum of 16-bit words used by IPv4 headers, UDP and TCP, catches many errors but not words swapped in order. A cyclic redundancy check such as CRC-8, CRC-16 or CRC-32 treats the data as a polynomial and sends the remainder of dividing it by a fixed polynomial; it detects every burst of errors no longer than its width, which is why Ethernet, CAN and many sensors use one.

A check value only detects damage. Recovering the data needs retransmission or an error-correcting code, and a CRC gives no protection against deliberate tampering, which requires a cryptographic authentication code. Implementations must match the specification exactly, including polynomial, initial value, bit reflection and final XOR, and mismatches in these details are the usual reason a CRC "never matches". You can compute a simple checksum by hand and implement a sensor's CRC-8 from its datasheet, confirming it against the datasheet's test value.` },
  { id: 'c-reliable-delivery', name: 'Reliable delivery over unreliable links', icon: 'network', refs: ['RFC9293', 'CS2023'],
    after: { 'c-checksums': 'Corrupted messages must be detected before they can be discarded and resent.', 'c-packets': 'Reliability mechanisms work on individual packets that can be lost or reordered.' },
    summary: 'Build reliable communication from sequence numbers, acknowledgements, timeouts, and retransmission, and handle the resulting duplicates safely.',
    details: `A link may lose, corrupt, duplicate or reorder messages, and reliable delivery is built on top from a few mechanisms. A checksum lets the receiver discard damaged messages. Sequence numbers reveal gaps, duplicates and reordering. Acknowledgements tell the sender what has arrived, and a timeout makes it resend anything unacknowledged, which is called automatic repeat request. Stop-and-wait sends one message at a time; a sliding window keeps several unacknowledged messages in flight so a slow round trip does not limit throughput.

Retransmission means the receiver will sometimes see the same message twice, so it must recognize duplicates by sequence number, and absolute commands such as "set speed to 0.5 m/s" are safer than relative ones such as "increase speed by 0.1". Reliability also costs time: waiting for a resent packet delays everything behind it. For a stream where only the newest value matters, such as a pose estimate, a late retransmission is worse than a dropped packet. You can design a stop-and-wait protocol for a serial link, trace what happens when an acknowledgement is lost and decide which robot messages deserve retransmission.` },
  { id: 'c-transport', name: 'UDP and TCP transport', icon: 'network', refs: ['RFC768', 'RFC9293', 'RFC8085', 'MAN7'],
    after: { 'c-reliable-delivery': 'TCP is the standard example of the reliability mechanisms, and UDP is the absence of them.', 'c-ip-addressing': 'Both protocols reach a program through an address and a port.' },
    summary: 'Choose between UDP datagrams and TCP byte streams by what they guarantee about delivery, order, message boundaries, and delay.',
    details: `UDP sends independent datagrams to an address and port. Each datagram arrives whole or not at all, so message boundaries are preserved, but UDP does not guarantee delivery, order or freedom from duplicates, and it has no connection setup. That suits periodic telemetry, video and discovery, where the application tolerates loss. TCP sets up a connection with a handshake and then provides a reliable, ordered byte stream using sequence numbers, acknowledgements and retransmission, together with flow control and congestion control.

A TCP byte stream has no message boundaries: one send can arrive split over several reads, and several sends can arrive merged in one. A single lost segment also holds back all the data behind it until it is resent, which is called head-of-line blocking, and small writes may be delayed by Nagle's algorithm unless it is disabled. ROS 2's default DDS middleware uses UDP between computers and adds its own configurable reliability. You can choose a protocol for teleoperation commands, a map download and a camera stream, and explain why a TCP read can return half a message.` },
  { id: 'c-framing', name: 'Message framing and serialization', icon: 'network', refs: ['RFC9293', 'MAN7', 'ROS2'],
    after: { 'c-byte-order': 'Binary serialization needs a defined byte order and field layout.', 'c-strings': 'Text formats such as JSON lines are built and parsed as strings.' },
    helpedBy: { 'c-checksums': 'A frame usually carries a check value so a damaged message can be rejected.' },
    summary: 'Turn structured messages into bytes and back, and mark where each message starts and ends in a continuous byte stream.',
    details: `Serialization converts structured data into bytes. Text formats such as JSON or CSV lines are readable and easy to debug, but larger and slower to parse; binary formats such as packed structures, Protocol Buffers, CBOR or the CDR encoding used by ROS 2 are compact and typed. Either way, a schema and a version number let both ends agree on what the bytes mean as the format evolves.

On a byte stream such as a TCP connection or a serial link, the receiver also needs to know where each message ends. The common methods are a delimiter such as a newline, which needs escaping or an encoding such as COBS for binary data, a length prefix, where the reader reads a header and then exactly that many bytes, and fixed-size messages. A start marker and a checksum let a receiver resynchronize after garbage. The receiving code must keep a buffer, because one read may deliver half a message or two and a half. You can design a serial packet with a start byte, length, payload and CRC, and write a parser that handles split and merged reads.` },
  { id: 'c-sockets', name: 'Socket programming', icon: 'network', refs: ['MAN7', 'PYTUT', 'CS2023'],
    after: { 'c-transport': 'A socket is opened for UDP or TCP and inherits its guarantees.', 'c-errors': 'Network calls fail in many ways that must be handled, from refused connections to timeouts.', 'c-framing': 'Reading complete messages from a TCP socket requires framing.' },
    helpedBy: { 'c-event-loops': 'Servers with many connections are often built on an event loop.' },
    summary: 'Exchange data over TCP and UDP from your own programs, handling blocking calls, partial reads, timeouts, and connections that close or fail.',
    details: `A socket is the operating system's handle for a network endpoint. A TCP server creates a socket, binds it to an address and port, listens, and calls accept, which returns a new socket for each client; a client simply connects. recv returns up to the requested number of bytes, possibly fewer, and returns zero bytes when the other side has closed the connection. sendall keeps sending until everything is written. UDP uses sendto and recvfrom, one datagram per call.

By default these calls block, and a recv on a silent connection waits forever, so real programs set timeouts or use non-blocking sockets with select or an event loop. Errors are part of normal operation: connection refused means nothing is listening, a reset means the peer vanished, and a timeout means the network or the peer is too slow. Binding to 0.0.0.0 accepts connections on all interfaces, while 127.0.0.1 accepts only local ones. You can write a TCP client and server that exchange length-prefixed messages and survive the server restarting, and a UDP receiver that ignores malformed datagrams.` },
  { id: 'c-latency', name: 'Latency, bandwidth, and jitter', icon: 'network', refs: ['RFC7679', 'RFC3393', 'CS2023'],
    after: { 'c-packets': 'Delay accumulates per packet as it is transmitted, queued, and forwarded.' },
    helpedBy: { 'm-quantile': 'Percentiles describe the tail of a delay distribution far better than the mean.' },
    summary: 'Distinguish latency, bandwidth, and jitter, measure them, and estimate how they limit a networked or real-time system.',
    details: `Latency is the time a message takes to arrive, made up of propagation, transmission, queuing and processing delays. Bandwidth or throughput is how much data per second a path carries, and jitter is how much the latency varies. They are independent: a 1 MB image on a 10 Mbit/s link takes about 0.8 s to transmit, ignoring protocol overhead, however short the distance, while a tiny command can still wait behind a full queue. Round-trip time, as ping reports it, includes both directions.

Averages hide what breaks systems. Wi-Fi latency may usually be a few milliseconds yet spike to hundreds under interference, so delays are reported as distributions with percentiles such as the 99th. Large buffers in routers smooth throughput but add queuing delay. For teleoperation and remote control, latency and jitter limit how quickly a loop closed over the network can react, which is why safety-critical loops run on the robot itself. You can compute a message's transmission time, measure a round-trip distribution, report its median and 99th percentile and judge which loops a given network could close.` }
];
