// Systems programming and operating-system foundations. Original descriptions; references are
// coverage checks only.
export const subdomain = 'Systems programming';
export const nodes = [
  { id: 'c-c-language', name: 'C language essentials', icon: 'code', refs: ['WG14C', 'CS2023'],
    after: { 'c-loops': 'C programs use the same loops and conditions, written in C syntax.', 'c-functions': 'A C program is organized entirely into functions, starting from main.', 'c-terminal': 'C programs are compiled and run from the command line.' },
    summary: 'Write, compile, and run small C programs with declared variables, functions, arrays, strings, and printf, and act on the compiler\'s warnings.',
    details: `A C program starts at main(), every statement ends with a semicolon, and every variable is declared with a type before it is used. printf formats output with conversion specifiers such as %d for an int and %.2f for a double, and a mismatched specifier prints garbage instead of raising an error. Arrays have a fixed size and no bounds checking, and strings are arrays of char ending in a zero byte, so a word of 5 letters needs 6 bytes. Header files (.h) declare functions that .c files define, and #include pastes a header in before compilation, a job of the preprocessor, which also handles #define constants.

A single file compiles and runs with gcc -Wall -Wextra -o average main.c followed by ./average. C trusts the programmer: an uninitialized local variable holds whatever was in memory, writing past the end of an array silently corrupts neighbouring data, and calling a function whose header was not included draws a warning or an error, depending on the compiler and C standard. Treating warnings as errors catches most of these early. You can write a program that reads numbers from its command-line arguments into an array, prints their average to two decimal places and compiles without warnings.` },
  { id: 'c-static-types', name: 'Static types and fixed-width integers', icon: 'code', refs: ['WG14C', 'CS2023'],
    after: { 'c-integers': 'Fixed-width types are chosen by the range each integer representation can hold.', 'c-c-language': 'The declarations and conversion rules here are those of C and C++.' },
    helpedBy: { 'c-build': 'Static type errors are reported by the compiler during a build.' },
    summary: 'Declare variables with static types, choose fixed-width integer types, and predict implicit conversions in languages such as C and C++.',
    details: `In statically typed languages such as C, C++, Rust and Java, each variable's type is fixed when the program is compiled, and the compiler rejects mismatches before the program ever runs. C's basic integer types have platform-dependent sizes: int is 16 bits on some microcontrollers and 32 bits on most computers. The fixed-width types in stdint.h, such as uint8_t, int16_t and uint32_t, make sizes explicit, which matters for hardware registers, file formats and messages.

C also converts types silently. Arithmetic on small types is carried out in int (integer promotion), converting a float to an integer truncates, and comparing an int with an unsigned int converts the int to unsigned, so -1 < 1u is false, although in -1 < (uint8_t)1 both sides are first promoted to int and the result is true. Compiler warnings such as -Wall -Wextra -Wconversion catch many of these. You can choose appropriate types for an encoder count, a 12-bit ADC reading and a temperature in hundredths of a degree, and predict the result of a mixed signed and unsigned expression.` },
  { id: 'c-pointers', name: 'Pointers and addresses', icon: 'memory', refs: ['WG14C', 'CS2023'],
    after: { 'c-memory': 'A pointer is a memory address, so the address model comes first.', 'c-static-types': 'Every pointer has a type that decides how the memory it points to is read.', 'c-references': 'Shared references in higher-level languages are the same idea with safety rules added.' },
    summary: 'Use pointers to refer to memory locations, dereference them safely, and relate pointers to arrays and function arguments.',
    details: `In C a pointer holds the address of an object: after int *p = &x, the expression *p = 5 changes x. Passing a pointer lets a function modify the caller's variable, as in swap(&a, &b), or avoid copying a large structure. An array name used in an expression becomes a pointer to its first element, and p[i] means *(p + i), where pointer arithmetic moves in steps of the element size, not in bytes.

Pointer bugs are among the most serious in systems code. Dereferencing a null pointer crashes a desktop program and on a microcontroller may silently read address zero. A dangling pointer outlives the object it pointed to, for example the address of a local variable returned from a function, and writing past the end of an array corrupts whatever lies next in memory. const says what a function may not modify, and C++ smart pointers and Rust's borrow rules exist to rule out these errors. You can write and explain swap(int *a, int *b), trace what *(p + 2) reads and spot a function that returns a pointer to its own local variable.` },
  { id: 'c-memory-layout', name: 'Stack, heap, and static memory', icon: 'memory', refs: ['OSTEP', 'MIT6004', 'CS2023'],
    after: { 'c-scope': 'Where a variable is stored follows from its scope and lifetime.', 'c-memory': 'The stack, heap, and static areas are regions of the address space.' },
    helpedBy: { 'c-recursion': 'Deep recursion is the most familiar way to exhaust the stack.' },
    summary: 'Place each variable in static storage, the stack, or the heap, and predict its lifetime and the failures each region can cause.',
    details: `A running program uses three kinds of storage. Static storage holds globals and static variables for the whole run: constants often stay in flash on a microcontroller, while other globals are copied or zeroed into RAM at startup. The stack holds each function call's frame, with its local variables, arguments and return address; it is fast and automatic but limited, often a few kilobytes per task on a small microcontroller and a few megabytes for a desktop program's main thread. The heap holds memory requested at run time, which lives until it is released.

Each region fails in its own way. Deep recursion or a large local array overflows the stack, a pointer to a local variable dangles once its function returns, and repeated heap allocation of different sizes can fragment memory until a request fails even though enough bytes are free in total. On microcontrollers the stack and heap may grow toward each other with nothing to detect a collision. You can say where each variable in a short C program lives, whether it survives the function's return, and why a 10 kB local buffer crashes a small real-time task.` },
  { id: 'c-allocation', name: 'Dynamic memory allocation and ownership', icon: 'memory', refs: ['WG14C', 'OSTEP', 'CS2023'],
    after: { 'c-pointers': 'Allocation returns a pointer that must be used and released correctly.', 'c-memory-layout': 'Allocated memory lives on the heap, whose lifetime rules differ from the stack.' },
    summary: 'Allocate and free heap memory correctly, assign clear ownership, and avoid leaks, double frees, and use-after-free errors.',
    details: `In C, malloc(n * sizeof *p) requests memory and returns a pointer, or NULL if it fails, and free releases it exactly once. realloc may move a block, so any other pointers into the old block become invalid. The classic errors are a leak, where the last pointer to a block is lost, a double free, a use after free and writing beyond the allocated size. All but the leak are undefined behaviour and a frequent source of security vulnerabilities, and tools such as AddressSanitizer and Valgrind find them.

The underlying discipline is ownership: for every allocation, one clearly identified piece of code is responsible for releasing it, and function interfaces document whether they transfer that responsibility. C++ encodes ownership with RAII and std::unique_ptr, Rust enforces it at compile time, and garbage-collected languages free memory automatically but can still hold on to it through forgotten references. Embedded firmware often avoids the heap after startup, using fixed pools, because allocation time and fragmentation are hard to bound. You can write a function that returns a new buffer, document who frees it and find the bug in code that reads a block after freeing it.` },
  { id: 'c-kernel', name: 'Operating system kernel and system calls', icon: 'chip', refs: ['OSTEP', 'CS2023'],
    after: { 'c-files': 'File operations are the most familiar service a program requests from the operating system.', 'c-memory': 'Protecting memory is one of the kernel\'s central jobs.' },
    helpedBy: { 'c-processor': 'Privileged and unprivileged modes are enforced by the processor itself.' },
    summary: 'Explain what an operating system kernel does, how programs request its services through system calls, and why user programs run with restricted privileges.',
    details: `An operating system shares the computer among programs: processor time, memory, files, devices and network connections. Its core, the kernel, runs in a privileged processor mode, while applications run in user mode and cannot touch hardware or other programs' memory directly. When a program needs a service, such as opening a file, reading from a serial port or starting another program, it makes a system call, a controlled entry into the kernel. Library functions such as fopen() or Python's open() are wrappers around these calls.

Crossing into the kernel has a cost, which is why buffered I/O that writes a block at a time is much faster than a system call per character. Open files, sockets and devices are referred to by handles or file descriptors, and on Unix-like systems devices appear as files such as /dev/ttyUSB0. A bare-metal microcontroller program has no kernel at all, and a real-time operating system provides a much smaller one. You can trace a Python serial read down to the system call, list a program's system calls with strace on Linux and explain why a user program cannot write to a device register on a PC.` },
  { id: 'c-virtual-memory', name: 'Virtual memory and address spaces', icon: 'memory', refs: ['OSTEP', 'MIT6004', 'CS2023'],
    after: { 'c-kernel': 'The kernel creates and manages each process\'s address space.', 'c-memory-layout': 'The regions of a program are what virtual memory maps into pages.' },
    helpedBy: { 'c-caches': 'The translation lookaside buffer is a cache for address translations.' },
    summary: 'Explain how each process gets its own virtual address space mapped to physical memory in pages, and what page faults and segmentation faults mean.',
    details: `On computers with a memory management unit, the addresses a program uses are virtual. The hardware translates them to physical addresses page by page, commonly 4 KiB at a time, using page tables that the kernel maintains, and a translation lookaside buffer caches recent translations. Because each process has its own page tables, two processes can use the same virtual address without interfering, and a bug in one cannot overwrite another's memory. Pages can also be marked read-only or non-executable.

Touching an address that is not mapped, or writing to a read-only page, causes a fault. The kernel either handles it, for example by loading a page on demand, or ends the program with a segmentation fault, which is what a null-pointer dereference usually produces. Demand loading and swapping to disk make memory access times unpredictable, which is why real-time Linux processes lock their memory in place. Most microcontrollers have no MMU and at most a memory protection unit that guards regions without translating them. You can explain process isolation, the cause of a segmentation fault and why page faults matter for a control loop.` },
  { id: 'c-processes', name: 'Processes and program execution', icon: 'chip', refs: ['OSTEP', 'MISSING', 'CS2023'],
    after: { 'c-kernel': 'Processes are created, scheduled, and ended by the kernel.', 'c-shell-pipes': 'Exit codes, arguments, and standard streams are the process interface first met in the shell.' },
    summary: 'Start, monitor, and stop processes, and use their arguments, environment, exit status, and signals.',
    details: `A process is a running instance of a program with its own address space, open files and at least one thread. The operating system creates it, with fork and exec on Unix-like systems or CreateProcess on Windows, and in Python subprocess.run() starts a child process, passes arguments and collects its output and exit code. Each process has a working directory and environment variables, and ps, top or Task Manager show what is running.

Processes are told to stop through signals or equivalent mechanisms: Ctrl+C sends SIGINT and service managers send SIGTERM. A program that holds hardware should catch these and shut down in order, for example closing its serial port and returning actuators to their idle state, instead of dying mid-command. Because processes are isolated, a crash in one does not corrupt another, so robot software is often split into many processes that talk through pipes, sockets or middleware. You can launch a child program, capture its output and status, stop it cleanly after a timeout and make your own program handle Ctrl+C safely.` },
  { id: 'c-threads', name: 'Threads', icon: 'chip', refs: ['OSTEP', 'PYTUT', 'CS2023'],
    after: { 'c-processes': 'Threads run inside a process and share its resources.', 'c-functions': 'A thread starts by running a given function.' },
    related: { 'c-event-loops': 'Threads and event loops are two ways to overlap waiting; they are combined when blocking work is moved to a worker thread.' },
    summary: 'Run work concurrently in threads that share a process\'s memory, wait for them with join, and stop them by request rather than by force.',
    details: `A thread is an independent flow of execution inside a process. Threads share the process's memory and open files but each has its own stack and registers. Creating one, with threading.Thread in Python, std::thread in C++ or pthread_create in C, runs a function concurrently with the rest of the program, and joining waits for it to finish. Typical uses are reading a sensor continuously while the main loop computes, or keeping a user interface responsive during slow work.

Sharing memory makes communication cheap but removes the isolation that separate processes provide, so one thread can corrupt data another is using. On a multicore processor threads can run in parallel, although the default CPython build runs only one thread's Python code at a time (free-threaded builds exist from Python 3.13), so threads there help with waiting on I/O rather than with computation. A thread should be stopped by asking it to finish, for example with an event flag it checks, never by killing it while it holds resources. You can run a reader thread that fills a queue while the main thread processes the items, and shut both down cleanly.` },
  { id: 'c-os-scheduling', name: 'CPU scheduling and context switches', icon: 'clock', refs: ['OSTEP', 'CS2023'],
    after: { 'c-threads': 'The scheduler decides which of the runnable threads uses each processor core.' },
    summary: 'Explain how an operating system shares processor time among threads through preemption, time slices, and priorities, and what a context switch costs.',
    details: `When there are more runnable threads than processor cores, the scheduler decides which runs next. Each thread is running, ready to run or blocked waiting for something such as I/O, a timer or a lock, and a blocked thread uses no processor time at all. A preemptive scheduler interrupts a running thread when its time slice ends or when a higher-priority thread becomes ready. Each context switch saves one thread's registers and stack pointer and restores another's, taking microseconds and leaving the caches holding the wrong data.

General-purpose schedulers aim for fairness and throughput, not deadlines, so a thread that asks to sleep for 10 ms may wake later than that on a busy system, and a loop built on sleep drifts and jitters. Real-time scheduling policies and priorities, such as SCHED_FIFO on Linux, change this but can starve other work if misused. You can explain why a 100 Hz loop timed with sleep runs unevenly on a loaded desktop, and why a thread blocked on a read costs nothing until data arrives.` },
  { id: 'c-race-conditions', name: 'Race conditions and shared data', icon: 'clock', refs: ['OSTEP', 'CS2023'],
    after: { 'c-threads': 'Races arise when threads that share memory interleave unpredictably.' },
    summary: 'Recognize concurrent code whose result depends on timing, and identify the shared data and non-atomic operations that cause it.',
    details: `A race condition occurs when the outcome depends on how concurrent activities happen to interleave. counter += 1 looks like one step, but it is a read, an add and a write, so two threads can both read 5 and both write 6, losing an update. Check-then-act code such as "if the queue is not full, append" has the same flaw, because the state can change between the check and the action. A reader can also see a half-finished update: if one thread writes a pose's x and then its y while another reads both, the reader can combine the new x with the old y, a pose the robot never had.

Races are intermittent: they may appear once a week, or disappear when a debugger or print statement changes the timing, so reasoning about them beats testing for them. In C and C++, unsynchronized conflicting access to shared data is undefined behaviour. The remedies are to share less, for example by passing messages through a queue, to share only immutable data, or to protect shared data with atomic operations or locks. You can draw a timeline showing a lost update and identify which variable in an interrupt-plus-main-loop program needs protection.` },
  { id: 'c-synchronization', name: 'Locks, semaphores, and condition variables', icon: 'clock', refs: ['OSTEP', 'FREERTOS', 'CS2023'],
    after: { 'c-race-conditions': 'Synchronization tools exist to prevent the races that must first be recognized.' },
    summary: 'Protect shared data with mutexes, wait for conditions without busy-waiting, and coordinate producers and consumers.',
    details: `A mutex lets only one thread at a time into a critical section that touches shared data. Critical sections should be short and should release the lock on every path, which with-blocks in Python and RAII lock guards in C++ ensure even when an exception occurs. A condition variable lets a thread sleep until another thread signals that something has changed: waiting releases the lock while asleep, and the condition must be rechecked in a loop after waking, because wakeups can be spurious. A counting semaphore tracks how many units of a resource are available.

For the common producer and consumer pattern, a thread-safe queue such as Python's queue.Queue packages all of this. Single-word flags and counters can use atomic variables without a lock. Interrupt handlers must never block on a mutex, so data shared with an ISR is protected by briefly disabling interrupts or passed through a lock-free ring buffer. You can fix a lost-update counter with a lock, build a bounded producer and consumer and explain why sleeping or doing slow I/O while holding a lock stalls other threads.` },
  { id: 'c-deadlock', name: 'Deadlock and lock ordering', icon: 'clock', refs: ['OSTEP', 'CS2023'],
    after: { 'c-synchronization': 'Deadlock is a failure mode of using locks.' },
    related: { 'm-dag': 'A deadlock-free locking scheme orders locks so the "acquired before" relation between them has no cycle.' },
    summary: 'Recognize how threads can block each other forever, and prevent deadlock with lock ordering, timeouts, and simpler designs.',
    details: `A deadlock occurs when each thread in a group holds a resource that another needs and waits for it forever: thread 1 holds lock A and waits for B while thread 2 holds B and waits for A. It requires four conditions together: exclusive resources, holding one resource while waiting for another, no forcible release and a circular wait. Breaking any one prevents it, and the usual practical rule is to acquire locks in one agreed global order, or to hold only one lock at a time.

Other defences are timeouts with try-lock so a thread can back off, and never calling unknown code, such as a callback, while holding a lock. Related failures are livelock, where threads keep reacting to each other without progress, and starvation, where one thread never gets its turn. A deadlocked program simply stops, and a dump of all threads shows each one waiting on a lock. You can find the deadlock in two functions that lock A then B and B then A, fix it by ordering and explain why holding one lock at a time avoids the problem.` },
  { id: 'c-event-loops', name: 'Event loops and asynchronous I/O', icon: 'code', refs: ['PYTUT', 'ROS2', 'CS2023'],
    after: { 'c-functions': 'An event loop runs handler functions, or coroutines, when their events occur.' },
    helpedBy: { 'c-queues': 'An event loop takes pending events and ready tasks from queues in order.' },
    summary: 'Structure a program around an event loop that runs callbacks or coroutines when data arrives or timers fire, without blocking the loop.',
    details: `An event loop repeatedly waits for something to happen, such as a socket becoming readable, a timer expiring or a message arriving, and dispatches the handler for it. In Python's asyncio, functions defined with async def are coroutines that pause at await while they wait, letting the loop run other work. Graphical interfaces, Node.js servers and ROS 2 executors, which run a node's callbacks when you call spin, are all built this way.

When the loop runs on a single thread, handlers take turns and cannot interrupt each other mid-operation, although shared state can still change at every await, and a multi-threaded executor, such as ROS 2's MultiThreadedExecutor, runs callbacks in parallel. On a single thread, one handler that blocks stalls all the others. A time.sleep(), a blocking read or a long calculation inside a callback delays every timer and message behind it, so blocking work is moved to a worker thread or process. You can write two periodic tasks at different rates with asyncio, demonstrate how a blocking call in one delays the other and fix it by awaiting or offloading the slow work.` }
];
