// Offline descriptions for the initial reference subjects. These explain scope;
// they are not assessment criteria or an exhaustive robotics curriculum.
export const PROFILES = {
 arithmetic: ['calculator', 'Arithmetic',
  'Arithmetic covers operations on numbers: addition, subtraction, multiplication, division, fractions, decimals, ratios, and percentages. These operations let you express quantities and compare them consistently. Reliable arithmetic also includes estimating the size of an answer and noticing when a result is unreasonable.',
  'In robotics, arithmetic appears in gear ratios, component counts, timing intervals, sensor readings, and unit conversions. It supports later algebra because manipulating equations still depends on understanding numerical operations. Being comfortable with arithmetic makes it easier to check both software output and physical measurements.'],
 algebra: ['function', 'Algebra',
  'Algebra describes relationships using symbols, expressions, equations, and functions. A variable represents a quantity that can change or is not yet known. Rearranging equations lets you solve for different quantities without inventing a new method for every numerical example.',
  'Robotics uses algebra to relate distance, time, speed, electrical quantities, and sensor calibration. It also provides the language needed for more advanced mathematical models. The starter map gives algebra prerequisite connections to calculus and linear algebra; these are selected links rather than a complete list of preparation for either subject.'],
 geometry: ['triangle', 'Geometry & trigonometry',
  'Geometry studies shapes, lengths, angles, and spatial relationships. Trigonometry relates angles to side lengths and describes recurring patterns through sine and cosine. Together, these subjects help translate a drawing or physical arrangement into quantities you can calculate.',
  'For a robot, these ideas help describe wheel motion, link lengths, sensor fields of view, and the position of a tool. They support kinematics, where the arrangement of joints determines motion. This broad starter subject can later be split into geometry, radians, trigonometric functions, and coordinate geometry.'],
 calculus: ['function', 'Calculus',
  'Calculus studies continuous change and accumulation. Derivatives describe how quickly a quantity changes, while integrals combine small contributions over an interval. These ideas connect a function to its slope, its accumulated effect, and its behavior as the input varies.',
  'In robotics, position, velocity, and acceleration are linked through calculus. Calculus also helps describe energy, dynamic models, and feedback systems. The starter connection to control is a supporting relationship: introductory practical control can be explored before mastering the mathematical treatment of continuous systems.'],
 linear: ['matrix', 'Linear algebra',
  'Linear algebra studies vectors, matrices, systems of linear equations, and transformations. Vectors can describe several related quantities at once; matrices describe operations on those quantities. This provides a compact way to reason about space, measurements, and computational models.',
  'Robotics uses these tools for coordinate transformations, joint calculations, estimation, and perception. A camera measurement or robot pose often contains several numbers that must be transformed together. Later expansion can separate vector operations, matrix multiplication, linear systems, and the transformations used in robotics.'],
 measurement: ['ruler', 'Measurement & units',
  'Measurement connects a numerical value to a physical quantity and a unit. Useful measurement also considers resolution, repeatability, uncertainty, and the reference used. Dimensional reasoning checks whether quantities have been combined in a physically meaningful way.',
  'Robots depend on measurements of length, angle, voltage, time, and many other quantities. Confusing millimeters with meters or degrees with radians can invalidate an otherwise correct calculation. This subject sits among the foundations because nearly every physical subsystem needs consistent measurements and clear units.'],
 physics: ['motion', 'Classical mechanics',
  'Classical mechanics describes motion and the forces associated with it. Its core ideas include position, velocity, acceleration, force, torque, energy, and momentum. Models range from simplified point masses to rotating bodies and connected mechanical systems.',
  'Robotics applies mechanics when choosing actuators, predicting loads, understanding balance, and estimating how a machine will respond. It contributes to mechanical design and control, but those broad connections do not mean every topic in mechanics must be completed before starting a practical project.'],
 design: ['gear', 'Mechanical design',
  'Mechanical design turns a required function into a physical arrangement of parts. It considers geometry, loads, materials, joints, clearances, tolerances, and how components will be made and assembled. A successful design must fit and function under the conditions it will actually encounter.',
  'For robotics, this includes frames, mounts, transmissions, end effectors, and service access. Design decisions interact with motor selection, sensing, wiring, and maintenance. The starter map places mechanical design between material knowledge and actuation to represent that progression from physical parts toward working mechanisms.'],
 materials: ['layers', 'Materials & fabrication',
  'Materials knowledge concerns properties such as stiffness, strength, density, corrosion resistance, and temperature behavior. Fabrication concerns how material becomes a part through processes such as cutting, forming, machining, welding, and additive manufacturing. Each process introduces practical limits and tradeoffs.',
  'Robot hardware must be buildable as well as conceptually correct. Material and process choices affect weight, precision, repairability, and cost. This broad subject can later expand into individual materials, manufacturing processes, fastening methods, and inspection skills rather than remaining one large node.'],
 circuits: ['circuit', 'Basic circuits',
  'Basic circuits introduces voltage, current, resistance, power, and the behavior of simple electrical networks. Circuit diagrams describe how components are connected. Series and parallel relationships help explain how electrical quantities change across different parts of a circuit.',
  'Robot sensors, controllers, and actuators all rely on electrical connections. Circuit knowledge helps you interpret measurements, understand signal paths, and distinguish a power connection from a data signal. The starter map links this subject toward electronics while leaving detailed prerequisite chains for later expansion.'],
 electronics: ['sensor', 'Electronics & sensors',
  'Electronics uses components and circuits to condition, switch, generate, and measure signals. Sensors convert a physical quantity into a signal that can be interpreted. Useful sensing involves more than reading a number: range, noise, calibration, and response time all matter.',
  'Robots use sensors to observe their joints, surroundings, and internal conditions. Electronics connects those measurements to a controller and helps drive outputs. Later nodes can distinguish analog signals, digital interfaces, signal conditioning, encoders, inertial sensors, and other sensing methods.'],
 logic: ['code', 'Logic & programming',
  'Logic and programming describe how to express procedures and make decisions precisely. Foundational topics include variables, conditions, loops, functions, and the interpretation of program state. Debugging checks whether the implemented procedure matches the behavior you intended.',
  'Robotic software reads inputs, computes actions, and coordinates tasks. Even a small controller needs clear logic and predictable handling of different conditions. This starter subject supports embedded systems and can later separate general programming skills from languages, tools, and hardware-specific techniques.'],
 embedded: ['chip', 'Embedded systems',
  'An embedded system is a computing system integrated into a larger device. It connects software execution to physical inputs and outputs, often under timing, memory, and power constraints. Microcontrollers, device interfaces, and real-time behavior are common parts of the subject.',
  'In robotics, embedded systems read sensors, generate actuator commands, and coordinate local hardware behavior. Their connection to the physical world makes timing and error handling especially important. This subject bridges computing and electronics and supports both feedback control and perception pipelines.'],
 control: ['feedback', 'Feedback control',
  'Feedback control compares a measured system state with a desired state and uses the difference to adjust an input. The result depends on the controller, the physical system, and the measurement process. Response speed, stability, disturbances, and actuator limits shape the behavior.',
  'Robots use feedback to regulate quantities such as wheel speed and joint position. Practical tuning and mathematical analysis are related but distinct skills. Control connects computing, measurement, and mechanics, which is why the starter map treats it as an integrating subject above several contributing areas.'],
 kinematics: ['arm', 'Robot kinematics',
  'Robot kinematics describes motion and geometric relationships without first calculating the forces that cause the motion. Forward kinematics maps joint configuration to a resulting pose. Inverse kinematics asks which joint configurations can produce a desired pose.',
  'These relationships are central to positioning a robot arm and understanding the movement of linked mechanisms. Geometry, trigonometry, and linear algebra provide useful representations. Later expansion can distinguish coordinate frames, transformations, joint types, workspace, forward kinematics, and inverse kinematics.'],
 actuation: ['gear', 'Actuation & mechanisms',
  'Actuation converts available energy into useful motion or force. Mechanisms transmit or constrain that motion through arrangements such as gears, belts, screws, and linkages. Choosing a solution involves speed, torque or force, range of motion, efficiency, and mechanical limits.',
  'Robots need actuators and mechanisms that match their tasks and fit the surrounding structure. Their behavior also affects sensing and control. The starter connections combine mechanical design and electronics here before leading toward overall robot integration.'],
 perception: ['eye', 'Perception & estimation',
  'Perception extracts useful information from sensor data. Estimation infers quantities that may not be directly measured, such as position or velocity, while accounting for imperfect information. These tasks may combine multiple measurements with mathematical models.',
  'Robotics uses perception and estimation to understand surroundings and track system state. They draw on computing, mathematics, sensors, and often probability, which is not yet a separate starter node. The current map is intentionally incomplete and will gain these supporting subjects as the dataset expands.'],
 integration: ['robot', 'Robot integration',
  'Robot integration combines mechanical, electrical, and computational subsystems into a functioning whole. The work includes defining interfaces, coordinating timing, checking assumptions, and verifying behavior across subsystem boundaries. Individually working components do not automatically form a reliable system.',
  'A robot may combine mechanisms, control, kinematics, and perception in different proportions depending on its purpose. The starter map places integration near the top to show this convergence. That position represents the chosen reference structure, not a universal final level or a measured difficulty score.']
};

export function profileFor(node) {
  const p = PROFILES[node.id];
  return p && p[1] === node.name ? p : null;
}
